import React, { createContext, useContext, useEffect, useState } from 'react';

export type SupportedLanguage = 'English' | 'Bahasa Indonesia' | 'Spanish' | 'French' | 'Mandarin';

export interface LanguageOption {
  code: string;
  name: SupportedLanguage;
  nativeName: string;
  flag: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'id', name: 'Bahasa Indonesia', nativeName: 'Bahasa Indonesia', flag: '🇮🇩' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'zh', name: 'Mandarin', nativeName: '中文 (简体)', flag: '🇨🇳' },
];

export const translations: Record<SupportedLanguage, Record<string, string>> = {
  English: {
    // General / Common
    app_name: 'EcoEat',
    school_name: 'BBS PIK',
    save: 'Save',
    cancel: 'Cancel',
    done: 'Done',
    close: 'Close',
    customizable: 'Customizable',
    verified: 'Verified',
    back: 'Back',
    edit: 'Edit',
    level: 'Level',
    xp: 'XP',
    rank: 'Rank',
    streak: 'Streak',
    days: 'Days',
    days_left: 'days left',
    students: 'Students',
    rewards: 'Rewards',
    view_details: 'View Details',
    view_all: 'View All',
    awesome: 'Awesome',
    active: 'Active',
    change: 'Change',

    // Navigation
    nav_dashboard: 'Dashboard',
    nav_capture: 'Scan Meal',
    nav_leaderboard: 'Leaderboard',
    nav_profile: 'Profile',
    nav_settings: 'Settings',
    nav_menu: 'Menu',
    drawer_menu: 'Campus Menu',
    drawer_themes: 'Theme & Appearance',
    drawer_student_hub: 'BBS PIK Student Hub',

    // Dashboard
    greeting_morning: 'Good morning',
    greeting_afternoon: 'Good afternoon',
    greeting_evening: 'Good evening',
    greeting_subtitle: 'Ready to turn lunch into campus eco-impact today?',
    stat_food_saved: 'Food Saved',
    stat_saved_this_week: 'Saved this week',
    stat_level_title: 'Eco Warrior Level',
    stat_xp_to_next: 'XP to Level',
    stat_streak: 'Day Streak',
    portion_title: "Select Today's Dining Portion",
    portion_small: 'Small',
    portion_small_desc: 'Light bite / snack',
    portion_regular: 'Regular',
    portion_regular_desc: 'Standard hunger',
    portion_large: 'Large',
    portion_large_desc: 'Heavy meal',
    btn_scan_meal: 'Scan & Log Meal',
    btn_scan_meal_desc: 'AI portion recognition & clean plate scan',
    section_campus_challenge: 'Campus Sustainability Challenge',
    challenge_title: '1-Ton Food Divert Goal',
    challenge_diverted_so_far: 'kg diverted so far',
    section_recent_meals: 'Recent Meals Log',
    meal_clean_plate: 'Clean Plate',
    meal_co2_diverted: 'CO2 Diverted',
    section_daily_tips: 'Daily Campus Eco Tips',
    section_campus_special: "Today's Dining Hall Special",
    special_title: 'Farm-Fresh Organic Garden Salad',
    special_desc: 'Locally harvested organic crisp lettuce, cherry tomatoes, cucumbers, toasted chickpeas, and house-made lemon tahini vinaigrette.',
    special_plant_rich: '100% Plant-Rich',
    special_station: 'Station: Dining Hall North 2',

    // Capture & Camera Viewfinder
    capture_title: 'AI Meal Scanner',
    capture_step_1: '1. Pre-Meal Portion',
    capture_step_2: '2. Clean Plate Verification',
    capture_align_meal: 'Align meal within frame to identify items and estimate portion',
    capture_align_plate: 'Align empty plate to verify clean plate & award bonus XP',
    capture_btn_snap: 'Capture Photo',
    capture_btn_retake: 'Retake Photo',
    capture_analyzing: 'Analyzing with AI...',
    capture_dish_name: 'Recognized Dish',
    capture_calories: 'Est. Calories',
    capture_portion_weight: 'Est. Portion Weight',
    capture_ingredients: 'Identified Ingredients',
    capture_carbon_diverted: 'CO2 Emissions Diverted',
    capture_clean_plate_conf: 'Clean Plate Confidence',
    capture_waste_grams: 'Remaining Waste',
    capture_xp_reward: 'XP Earned',
    capture_btn_proceed: 'Looks Good, Enjoy Meal!',
    capture_btn_finish: 'Verify Clean Plate & Finish',
    capture_bonus_awarded: '+20 XP Clean Plate Bonus Unlocked!',
    capture_cancel: 'Cancel Scan',
    capture_demo_sample: 'Try Sample Dish',

    // Leaderboard
    lb_title: 'Campus Leaderboard',
    lb_tab_bbs: 'BBS PIK',
    lb_tab_goal: 'Campus Goal',
    lb_tab_class: 'Grade Classes',
    lb_top_champion: 'Current #1 Eco Warrior',
    lb_student_rankings: 'Student Rankings',
    lb_challenge_title: 'Campus 1-Ton Food Divert',
    lb_challenge_sub: 'BBS PIK Campus Sustainability Challenge',
    lb_your_rank: 'Your Campus Rank',
    lb_class_rankings: 'Grade Level Waste Diverted',

    // Profile
    profile_title: 'Student Eco Profile',
    profile_edit_picture_hint: 'Click to change photo',
    profile_edit_btn: 'Edit Profile',
    profile_summary: 'Sustainability Summary',
    profile_total_food_saved: 'Total Food Saved',
    profile_streak_days: 'Daily Streak',
    profile_badges_unlocked: 'Badges Earned',
    profile_current_tier: 'Current Tier',
    profile_badges_heading: 'Eco Badges',
    profile_view_all_badges: 'View All Badges',
    profile_meal_history: 'Meal History Log',

    // Settings
    settings_title: 'Settings',
    settings_account: 'Account',
    settings_edit_profile: 'Edit Profile & Picture',
    settings_change_password: 'Change Password',
    settings_school_id: 'School ID',
    settings_preferences: 'Preferences',
    settings_meal_reminders: 'Meal Reminders',
    settings_challenge_updates: 'Challenge Updates',
    settings_language: 'Language',
    settings_greeting_color: 'Greeting Name & Color',
    settings_theme: 'Theme & Appearance',
    settings_dark_mode: 'Dark Mode',
    settings_dark_desc: 'High contrast dark theme',
    settings_light_desc: 'Crisp daylight theme',
    settings_sustainability: 'Sustainability',
    settings_daily_goal: 'Daily Waste Goal',
    settings_campus_visibility: 'Campus Visibility',
    settings_campus_visibility_desc: 'Show on BBS Leaderboards',
    settings_support: 'Support',
    settings_faq: 'FAQ',
    settings_contact_us: 'Contact Us',
    settings_privacy: 'Privacy Policy',
    settings_sign_out: 'Sign Out',
    settings_sign_out_confirm: 'Are you sure you want to sign out of BBS PIK EcoEat?',

    // Modals
    modal_edit_profile: 'Edit Student Profile',
    modal_choose_avatar: 'Choose Avatar',
    modal_profile_pic: 'Profile Picture',
    modal_custom_photo_active: 'Custom Photo Active',
    modal_upload_photo: 'Upload Photo',
    modal_take_photo: 'Take Photo',
    modal_link: 'Link',
    modal_photo_instructions: 'Upload any personal image (PNG, JPG, WebP) from your device or camera.',
    modal_drag_drop: 'Drag & drop your picture here, or browse file',
    modal_supports_formats: 'Supports all image formats up to 8MB',
    modal_apply_url: 'Apply URL',
    modal_hide_presets: '▼ Hide Avatar Presets',
    modal_show_presets: '▶ Or choose a sample avatar preset',
    modal_full_name: 'Full Display Name',
    modal_greeting_name: 'Greeting Name (Dashboard)',
    modal_grade: 'Grade',
    modal_save_changes: 'Save Changes',
    modal_pw_title: 'Change Password',
    modal_current_pw: 'Current Password',
    modal_new_pw: 'New Password',
    modal_update_pw: 'Update Password',
    modal_pw_updated_title: 'Password Updated!',
    modal_pw_updated_desc: 'Your campus student credentials have been securely updated.',
    modal_greeting_accent_title: 'Greeting Accent Color',
    modal_greeting_accent_desc: 'Personalize the header greeting text style on your EcoEat dashboard.',
    modal_theme_title: 'Appearance & Themes',
    modal_theme_desc: 'Personalize the application color palette and visual atmosphere.',
    modal_badge_gallery_title: 'Campus Badges Gallery',
    modal_special_title: 'Campus Meal Hall Special',
    modal_close_special: 'Close Special',
    modal_reward_milestone: 'Reward Milestone',
    modal_rewards_list: 'School Community Rewards:',

    // Toasts
    toast_profile_updated: 'Profile updated successfully',
    toast_preferences_saved: 'Preferences saved',
    toast_language_changed: 'Language switched to',
    toast_greeting_updated: 'Greeting color updated!',
    toast_signed_out: 'Signed out successfully',
    toast_clean_verified: '✨ Clean plate verified! XP added to your campus ranking!',
    toast_level_up: '🎉 Level Up! You reached Level',
  },

  'Bahasa Indonesia': {
    // General / Common
    app_name: 'EcoEat',
    school_name: 'BBS PIK',
    save: 'Simpan',
    cancel: 'Batal',
    done: 'Selesai',
    close: 'Tutup',
    customizable: 'Dapat Disesuaikan',
    verified: 'Terverifikasi',
    back: 'Kembali',
    edit: 'Ubah',
    level: 'Tingkat',
    xp: 'XP',
    rank: 'Peringkat',
    streak: 'Runtunan',
    days: 'Hari',
    days_left: 'hari tersisa',
    students: 'Siswa',
    rewards: 'Hadiah',
    view_details: 'Lihat Detail',
    view_all: 'Lihat Semua',
    awesome: 'Keren',
    active: 'Aktif',
    change: 'Ubah',

    // Navigation
    nav_dashboard: 'Beranda',
    nav_capture: 'Pindai Makanan',
    nav_leaderboard: 'Papan Peringkat',
    nav_profile: 'Profil',
    nav_settings: 'Pengaturan',
    nav_menu: 'Menu',
    drawer_menu: 'Menu Kampus',
    drawer_themes: 'Tema & Tampilan',
    drawer_student_hub: 'Pusat Siswa BBS PIK',

    // Dashboard
    greeting_morning: 'Selamat pagi',
    greeting_afternoon: 'Selamat siang',
    greeting_evening: 'Selamat malam',
    greeting_subtitle: 'Siap mengubah makan siang menjadi dampak ramah lingkungan hari ini?',
    stat_food_saved: 'Makanan Diselamatkan',
    stat_saved_this_week: 'Diselamatkan minggu ini',
    stat_level_title: 'Tingkat Pejuang Lingkungan',
    stat_xp_to_next: 'XP menuju Tingkat',
    stat_streak: 'Hari Berturut-turut',
    portion_title: 'Pilih Porsi Makan Hari Ini',
    portion_small: 'Kecil',
    portion_small_desc: 'Camilan ringan',
    portion_regular: 'Biasa',
    portion_regular_desc: 'Porsi standar',
    portion_large: 'Besar',
    portion_large_desc: 'Porsi kenyang',
    btn_scan_meal: 'Pindai & Catat Makanan',
    btn_scan_meal_desc: 'Pengenalan porsi AI & piring bersih',
    section_campus_challenge: 'Tantangan Keberlanjutan Kampus',
    challenge_title: 'Target Pengurangan 1 Ton Makanan',
    challenge_diverted_so_far: 'kg dikurangi sejauh ini',
    section_recent_meals: 'Riwayat Makanan Terkini',
    meal_clean_plate: 'Piring Bersih',
    meal_co2_diverted: 'CO2 Dikurangi',
    section_daily_tips: 'Tips Ramah Lingkungan Harian',
    section_campus_special: 'Spesial Kantin Kampus Hari Ini',
    special_title: 'Salad Segar Organik Kebun',
    special_desc: 'Selada renyah organik lokal, tomat ceri, mentimun, buncis panggang, dan saus tahini lemon segar.',
    special_plant_rich: '100% Kaya Nabati',
    special_station: 'Lokasi: Kantin Utara 2',

    // Capture & Camera Viewfinder
    capture_title: 'Pemindai Makanan AI',
    capture_step_1: '1. Porsi Sebelum Makan',
    capture_step_2: '2. Verifikasi Piring Bersih',
    capture_align_meal: 'Arahkan makanan ke dalam bingkai untuk mengenali porsi',
    capture_align_plate: 'Arahkan piring kosong untuk verifikasi piring bersih & klaim bonus XP',
    capture_btn_snap: 'Ambil Foto',
    capture_btn_retake: 'Foto Ulang',
    capture_analyzing: 'Menganalisis dengan AI...',
    capture_dish_name: 'Makanan Terdeteksi',
    capture_calories: 'Perkiraan Kalori',
    capture_portion_weight: 'Perkiraan Berat Porsi',
    capture_ingredients: 'Bahan yang Teridentifikasi',
    capture_carbon_diverted: 'Emisi CO2 Berhasil Dikurangi',
    capture_clean_plate_conf: 'Tingkat Kebersihan Piring',
    capture_waste_grams: 'Sisa Makanan',
    capture_xp_reward: 'XP Didapatkan',
    capture_btn_proceed: 'Sesuai, Selamat Menikmati!',
    capture_btn_finish: 'Verifikasi Piring Bersih & Selesai',
    capture_bonus_awarded: '+20 XP Bonus Piring Bersih Terbuka!',
    capture_cancel: 'Batalkan Pemindaian',
    capture_demo_sample: 'Coba Contoh Makanan',

    // Leaderboard
    lb_title: 'Papan Peringkat Kampus',
    lb_tab_bbs: 'BBS PIK',
    lb_tab_goal: 'Target Kampus',
    lb_tab_class: 'Tingkat Kelas',
    lb_top_champion: 'Pejuang Lingkungan #1 Saat Ini',
    lb_student_rankings: 'Peringkat Siswa',
    lb_challenge_title: 'Target Pengurangan 1 Ton Makanan',
    lb_challenge_sub: 'Tantangan Keberlanjutan BBS PIK',
    lb_your_rank: 'Peringkat Kampus Anda',
    lb_class_rankings: 'Sampah Makanan Dikurangi per Tingkat',

    // Profile
    profile_title: 'Profil Siswa Eco',
    profile_edit_picture_hint: 'Klik untuk mengganti foto',
    profile_edit_btn: 'Ubah Profil',
    profile_summary: 'Ringkasan Keberlanjutan',
    profile_total_food_saved: 'Total Makanan Diselamatkan',
    profile_streak_days: 'Runtunan Harian',
    profile_badges_unlocked: 'Lencana Diraih',
    profile_current_tier: 'Tingkat Saat Ini',
    profile_badges_heading: 'Lencana Ramah Lingkungan',
    profile_view_all_badges: 'Lihat Semua Lencana',
    profile_meal_history: 'Riwayat Catatan Makanan',

    // Settings
    settings_title: 'Pengaturan',
    settings_account: 'Akun',
    settings_edit_profile: 'Ubah Profil & Foto',
    settings_change_password: 'Ubah Kata Sandi',
    settings_school_id: 'ID Sekolah',
    settings_preferences: 'Preferensi',
    settings_meal_reminders: 'Pengingat Makan',
    settings_challenge_updates: 'Pembaruan Tantangan',
    settings_language: 'Bahasa',
    settings_greeting_color: 'Nama & Warna Sapaan',
    settings_theme: 'Tema & Tampilan',
    settings_dark_mode: 'Mode Gelap',
    settings_dark_desc: 'Tema gelap kontras tinggi',
    settings_light_desc: 'Tema terang bersih',
    settings_sustainability: 'Keberlanjutan',
    settings_daily_goal: 'Target Sisa Harian',
    settings_campus_visibility: 'Visibilitas Kampus',
    settings_campus_visibility_desc: 'Tampilkan di Papan Peringkat BBS',
    settings_support: 'Bantuan',
    settings_faq: 'Tanya Jawab (FAQ)',
    settings_contact_us: 'Hubungi Kami',
    settings_privacy: 'Kebijakan Privasi',
    settings_sign_out: 'Keluar',
    settings_sign_out_confirm: 'Apakah Anda yakin ingin keluar dari BBS PIK EcoEat?',

    // Modals
    modal_edit_profile: 'Ubah Profil Siswa',
    modal_choose_avatar: 'Pilih Avatar',
    modal_profile_pic: 'Foto Profil',
    modal_custom_photo_active: 'Foto Khusus Aktif',
    modal_upload_photo: 'Unggah Foto',
    modal_take_photo: 'Ambil Foto',
    modal_link: 'Tautan',
    modal_photo_instructions: 'Unggah foto pribadi (PNG, JPG, WebP) dari perangkat atau kamera Anda.',
    modal_drag_drop: 'Tarik & lepas foto Anda di sini, atau cari berkas',
    modal_supports_formats: 'Mendukung semua format gambar hingga 8MB',
    modal_apply_url: 'Terapkan URL',
    modal_hide_presets: '▼ Sembunyikan Avatar Contoh',
    modal_show_presets: '▶ Atau pilih avatar contoh',
    modal_full_name: 'Nama Lengkap',
    modal_greeting_name: 'Nama Sapaan (Beranda)',
    modal_grade: 'Kelas',
    modal_save_changes: 'Simpan Perubahan',
    modal_pw_title: 'Ubah Kata Sandi',
    modal_current_pw: 'Kata Sandi Saat Ini',
    modal_new_pw: 'Kata Sandi Baru',
    modal_update_pw: 'Perbarui Kata Sandi',
    modal_pw_updated_title: 'Kata Sandi Diperbarui!',
    modal_pw_updated_desc: 'Kredensial siswa kampus Anda telah berhasil diperbarui.',
    modal_greeting_accent_title: 'Warna Aksen Sapaan',
    modal_greeting_accent_desc: 'Sesuaikan gaya warna teks sapaan pada beranda EcoEat Anda.',
    modal_theme_title: 'Tampilan & Tema',
    modal_theme_desc: 'Sesuaikan palet warna aplikasi dan atmosfer visual.',
    modal_badge_gallery_title: 'Galeri Lencana Kampus',
    modal_special_title: 'Spesial Kantin Kampus',
    modal_close_special: 'Tutup Spesial',
    modal_reward_milestone: 'Target Hadiah',
    modal_rewards_list: 'Hadiah Komunitas Sekolah:',

    // Toasts
    toast_profile_updated: 'Profil berhasil diperbarui',
    toast_preferences_saved: 'Preferensi disimpan',
    toast_language_changed: 'Bahasa diubah ke',
    toast_greeting_updated: 'Warna sapaan diperbarui!',
    toast_signed_out: 'Berhasil keluar',
    toast_clean_verified: '✨ Piring bersih terverifikasi! XP ditambahkan ke peringkat kampus!',
    toast_level_up: '🎉 Naik Tingkat! Anda mencapai Tingkat',
  },

  Spanish: {
    // General / Common
    app_name: 'EcoEat',
    school_name: 'BBS PIK',
    save: 'Guardar',
    cancel: 'Cancelar',
    done: 'Listo',
    close: 'Cerrar',
    customizable: 'Personalizable',
    verified: 'Verificado',
    back: 'Atrás',
    edit: 'Editar',
    level: 'Nivel',
    xp: 'XP',
    rank: 'Rango',
    streak: 'Racha',
    days: 'Días',
    days_left: 'días restantes',
    students: 'Estudiantes',
    rewards: 'Premios',
    view_details: 'Ver Detalles',
    view_all: 'Ver Todo',
    awesome: 'Genial',
    active: 'Activo',
    change: 'Cambiar',

    // Navigation
    nav_dashboard: 'Inicio',
    nav_capture: 'Escanear Comida',
    nav_leaderboard: 'Clasificación',
    nav_profile: 'Perfil',
    nav_settings: 'Ajustes',
    nav_menu: 'Menú',
    drawer_menu: 'Menú del Campus',
    drawer_themes: 'Tema y Apariencia',
    drawer_student_hub: 'Centro de Estudiantes BBS PIK',

    // Dashboard
    greeting_morning: 'Buenos días',
    greeting_afternoon: 'Buenas tardes',
    greeting_evening: 'Buenas noches',
    greeting_subtitle: '¿Listo para convertir tu almuerzo en impacto ecológico hoy?',
    stat_food_saved: 'Comida Salvada',
    stat_saved_this_week: 'Salvado esta semana',
    stat_level_title: 'Nivel de Guerrero Eco',
    stat_xp_to_next: 'XP para Nivel',
    stat_streak: 'Días de Racha',
    portion_title: 'Selecciona la Porción de Hoy',
    portion_small: 'Pequeña',
    portion_small_desc: 'Bocadillo ligero',
    portion_regular: 'Normal',
    portion_regular_desc: 'Apetito estándar',
    portion_large: 'Grande',
    portion_large_desc: 'Comida abundante',
    btn_scan_meal: 'Escanear y Registrar',
    btn_scan_meal_desc: 'Reconocimiento de porción por IA y plato limpio',
    section_campus_challenge: 'Desafío de Sostenibilidad del Campus',
    challenge_title: 'Meta de 1 Tonelada de Alimentos',
    challenge_diverted_so_far: 'kg desviados hasta ahora',
    section_recent_meals: 'Registro de Comidas Recientes',
    meal_clean_plate: 'Plato Limpio',
    meal_co2_diverted: 'CO2 Evitado',
    section_daily_tips: 'Consejos Ecológicos Diarios',
    section_campus_special: 'Especial del Comedor de Hoy',
    special_title: 'Ensalada Fresca Orgánica',
    special_desc: 'Lechuga crujiente local, tomates cherry, pepinos, garbanzos tostados y vinagreta de tahini y limón.',
    special_plant_rich: '100% Vegetal',
    special_station: 'Estación: Comedor Norte 2',

    // Capture & Camera Viewfinder
    capture_title: 'Escáner de Comida con IA',
    capture_step_1: '1. Porción Inicial',
    capture_step_2: '2. Verificación de Plato Limpio',
    capture_align_meal: 'Encuadra la comida para reconocerla y estimar la porción',
    capture_align_plate: 'Encuadra el plato vacío para verificar plato limpio y ganar XP adicional',
    capture_btn_snap: 'Tomar Foto',
    capture_btn_retake: 'Repetir Foto',
    capture_analyzing: 'Analizando con IA...',
    capture_dish_name: 'Plato Reconocido',
    capture_calories: 'Calorías Estimadas',
    capture_portion_weight: 'Peso Estimado',
    capture_ingredients: 'Ingredientes Identificados',
    capture_carbon_diverted: 'Emisiones de CO2 Evitadas',
    capture_clean_plate_conf: 'Confianza de Plato Limpio',
    capture_waste_grams: 'Desperdicio Restante',
    capture_xp_reward: 'XP Ganados',
    capture_btn_proceed: '¡Todo Bien, Buen Provecho!',
    capture_btn_finish: 'Verificar Plato Limpio y Finalizar',
    capture_bonus_awarded: '¡+20 XP Bonus de Plato Limpio Desbloqueado!',
    capture_cancel: 'Cancelar Escaneo',
    capture_demo_sample: 'Probar Plato de Ejemplo',

    // Leaderboard
    lb_title: 'Clasificación del Campus',
    lb_tab_bbs: 'BBS PIK',
    lb_tab_goal: 'Meta del Campus',
    lb_tab_class: 'Por Grado',
    lb_top_champion: 'Guerrero Eco #1 Actual',
    lb_student_rankings: 'Ranking de Estudiantes',
    lb_challenge_title: 'Desvío de 1 Tonelada de Comida',
    lb_challenge_sub: 'Desafío de Sostenibilidad BBS PIK',
    lb_your_rank: 'Tu Rango en el Campus',
    lb_class_rankings: 'Comida Salvada por Grado',

    // Profile
    profile_title: 'Perfil de Estudiante Eco',
    profile_edit_picture_hint: 'Haz clic para cambiar foto',
    profile_edit_btn: 'Editar Perfil',
    profile_summary: 'Resumen de Sostenibilidad',
    profile_total_food_saved: 'Total de Comida Salvada',
    profile_streak_days: 'Racha Diaria',
    profile_badges_unlocked: 'Insignias Ganadas',
    profile_current_tier: 'Nivel Actual',
    profile_badges_heading: 'Insignias Ecológicas',
    profile_view_all_badges: 'Ver Todas las Insignias',
    profile_meal_history: 'Historial de Comidas',

    // Settings
    settings_title: 'Ajustes',
    settings_account: 'Cuenta',
    settings_edit_profile: 'Editar Perfil y Foto',
    settings_change_password: 'Cambiar Contraseña',
    settings_school_id: 'ID Escolar',
    settings_preferences: 'Preferencias',
    settings_meal_reminders: 'Recordatorios de Comida',
    settings_challenge_updates: 'Actualizaciones de Desafíos',
    settings_language: 'Idioma',
    settings_greeting_color: 'Nombre y Color de Saludo',
    settings_theme: 'Tema y Apariencia',
    settings_dark_mode: 'Modo Oscuro',
    settings_dark_desc: 'Tema oscuro de alto contraste',
    settings_light_desc: 'Tema claro brillante',
    settings_sustainability: 'Sostenibilidad',
    settings_daily_goal: 'Meta Diaria de Desperdicio',
    settings_campus_visibility: 'Visibilidad en el Campus',
    settings_campus_visibility_desc: 'Mostrar en la clasificación de BBS',
    settings_support: 'Soporte',
    settings_faq: 'Preguntas Frecuentes',
    settings_contact_us: 'Contacto',
    settings_privacy: 'Política de Privacidad',
    settings_sign_out: 'Cerrar Sesión',
    settings_sign_out_confirm: '¿Estás seguro de que deseas cerrar sesión en BBS PIK EcoEat?',

    // Modals
    modal_edit_profile: 'Editar Perfil de Estudiante',
    modal_choose_avatar: 'Elegir Avatar',
    modal_profile_pic: 'Foto de Perfil',
    modal_custom_photo_active: 'Foto Personalizada Activa',
    modal_upload_photo: 'Subir Foto',
    modal_take_photo: 'Tomar Foto',
    modal_link: 'Enlace',
    modal_photo_instructions: 'Sube cualquier imagen personal (PNG, JPG, WebP) desde tu dispositivo o cámara.',
    modal_drag_drop: 'Arrastra y suelta tu foto aquí, o busca un archivo',
    modal_supports_formats: 'Soporta formatos de imagen de hasta 8MB',
    modal_apply_url: 'Aplicar URL',
    modal_hide_presets: '▼ Ocultar Avatares Predefinidos',
    modal_show_presets: '▶ O elige un avatar de muestra',
    modal_full_name: 'Nombre Completo',
    modal_greeting_name: 'Nombre de Saludo (Inicio)',
    modal_grade: 'Grado',
    modal_save_changes: 'Guardar Cambios',
    modal_pw_title: 'Cambiar Contraseña',
    modal_current_pw: 'Contraseña Actual',
    modal_new_pw: 'Nueva Contraseña',
    modal_update_pw: 'Actualizar Contraseña',
    modal_pw_updated_title: '¡Contraseña Actualizada!',
    modal_pw_updated_desc: 'Tus credenciales de estudiante han sido actualizadas de forma segura.',
    modal_greeting_accent_title: 'Color del Saludo',
    modal_greeting_accent_desc: 'Personaliza el color del texto de bienvenida en tu panel EcoEat.',
    modal_theme_title: 'Apariencia y Temas',
    modal_theme_desc: 'Personaliza la paleta de colores y el ambiente visual de la aplicación.',
    modal_badge_gallery_title: 'Galería de Insignias del Campus',
    modal_special_title: 'Especial del Comedor',
    modal_close_special: 'Cerrar Especial',
    modal_reward_milestone: 'Hito de Recompensa',
    modal_rewards_list: 'Recompensas de la Comunidad Escolar:',

    // Toasts
    toast_profile_updated: 'Perfil actualizado con éxito',
    toast_preferences_saved: 'Preferencias guardadas',
    toast_language_changed: 'Idioma cambiado a',
    toast_greeting_updated: '¡Color de saludo actualizado!',
    toast_signed_out: 'Sesión cerrada exitosamente',
    toast_clean_verified: '✨ ¡Plato limpio verificado! ¡XP sumado a tu ranking del campus!',
    toast_level_up: '🎉 ¡Subiste de nivel! Has alcanzado el Nivel',
  },

  French: {
    // General / Common
    app_name: 'EcoEat',
    school_name: 'BBS PIK',
    save: 'Enregistrer',
    cancel: 'Annuler',
    done: 'Terminé',
    close: 'Fermer',
    customizable: 'Personnalisable',
    verified: 'Vérifié',
    back: 'Retour',
    edit: 'Modifier',
    level: 'Niveau',
    xp: 'XP',
    rank: 'Rang',
    streak: 'Série',
    days: 'Jours',
    days_left: 'jours restants',
    students: 'Étudiants',
    rewards: 'Récompenses',
    view_details: 'Voir les Détails',
    view_all: 'Voir Tout',
    awesome: 'Super',
    active: 'Actif',
    change: 'Changer',

    // Navigation
    nav_dashboard: 'Accueil',
    nav_capture: 'Scanner Repas',
    nav_leaderboard: 'Classement',
    nav_profile: 'Profil',
    nav_settings: 'Paramètres',
    nav_menu: 'Menu',
    drawer_menu: 'Menu Campus',
    drawer_themes: 'Thème & Apparence',
    drawer_student_hub: 'Pôle Étudiant BBS PIK',

    // Dashboard
    greeting_morning: 'Bonjour',
    greeting_afternoon: 'Bon après-midi',
    greeting_evening: 'Bonsoir',
    greeting_subtitle: 'Prêt à transformer votre déjeuner en impact écologique aujourd’hui ?',
    stat_food_saved: 'Nourriture Sauvée',
    stat_saved_this_week: 'Sauvé cette semaine',
    stat_level_title: 'Niveau Éco Guerrier',
    stat_xp_to_next: 'XP pour Niveau',
    stat_streak: 'Jours Consécutifs',
    portion_title: "Sélectionnez la Portion d'Aujourd'hui",
    portion_small: 'Petite',
    portion_small_desc: 'Collation légère',
    portion_regular: 'Normale',
    portion_regular_desc: 'Faim standard',
    portion_large: 'Grande',
    portion_large_desc: 'Repas copieux',
    btn_scan_meal: 'Scanner et Enregistrer',
    btn_scan_meal_desc: 'Reconnaissance de portion IA & assiette propre',
    section_campus_challenge: 'Défi Durabilité du Campus',
    challenge_title: 'Objectif 1 Tonne de Nourriture Sauvée',
    challenge_diverted_so_far: 'kg sauvés à ce jour',
    section_recent_meals: 'Historique des Repas Récents',
    meal_clean_plate: 'Assiette Propre',
    meal_co2_diverted: 'CO2 Évité',
    section_daily_tips: 'Conseils Éco du Jour',
    section_campus_special: 'Spécial Réfectoire du Jour',
    special_title: 'Salade Fraîche du Jardin Bio',
    special_desc: 'Laitue croquante locale, tomates cerises, concombres, pois chiches rôtis et vinaigrette maison tahini-citron.',
    special_plant_rich: '100% Végétal',
    special_station: 'Lieu : Réfectoire Nord 2',

    // Capture & Camera Viewfinder
    capture_title: 'Scanner de Repas IA',
    capture_step_1: '1. Portion Avant Repas',
    capture_step_2: '2. Vérification Assiette Propre',
    capture_align_meal: 'Cadrez le repas pour identifier les ingrédients et estimer la portion',
    capture_align_plate: "Cadrez l'assiette vide pour vérifier la propreté et gagner des bonus XP",
    capture_btn_snap: 'Prendre la Photo',
    capture_btn_retake: 'Reprendre la Photo',
    capture_analyzing: 'Analyse IA en cours...',
    capture_dish_name: 'Plat Reconnu',
    capture_calories: 'Calories Estimées',
    capture_portion_weight: 'Poids Estimé',
    capture_ingredients: 'Ingrédients Identifiés',
    capture_carbon_diverted: 'Émissions CO2 Évitées',
    capture_clean_plate_conf: 'Score Assiette Propre',
    capture_waste_grams: 'Déchets Restants',
    capture_xp_reward: 'XP Gagnés',
    capture_btn_proceed: 'Parfait, Bon Appétit !',
    capture_btn_finish: 'Valider Assiette Propre & Terminer',
    capture_bonus_awarded: '+20 XP Bonus Assiette Propre Débloqué !',
    capture_cancel: "Annuler l'Analyse",
    capture_demo_sample: 'Essayer Plat Démo',

    // Leaderboard
    lb_title: 'Classement du Campus',
    lb_tab_bbs: 'BBS PIK',
    lb_tab_goal: 'Objectif Campus',
    lb_tab_class: 'Par Classe',
    lb_top_champion: 'Guerrier Éco #1 Actuel',
    lb_student_rankings: 'Classement des Élèves',
    lb_challenge_title: '1 Tonne de Nourriture Sauvée',
    lb_challenge_sub: 'Défi Durabilité BBS PIK',
    lb_your_rank: 'Votre Rang sur le Campus',
    lb_class_rankings: 'Nourriture Sauvée par Niveau',

    // Profile
    profile_title: 'Profil Éco Élève',
    profile_edit_picture_hint: 'Cliquez pour changer la photo',
    profile_edit_btn: 'Modifier le Profil',
    profile_summary: 'Résumé de Durabilité',
    profile_total_food_saved: 'Total Nourriture Sauvée',
    profile_streak_days: 'Série Quotidienne',
    profile_badges_unlocked: 'Badges Obtenus',
    profile_current_tier: 'Rang Actuel',
    profile_badges_heading: 'Badges Écologiques',
    profile_view_all_badges: 'Voir Tous les Badges',
    profile_meal_history: 'Historique des Repas',

    // Settings
    settings_title: 'Paramètres',
    settings_account: 'Compte',
    settings_edit_profile: 'Modifier Profil & Photo',
    settings_change_password: 'Changer Mot de Passe',
    settings_school_id: 'Identifiant Scolaire',
    settings_preferences: 'Préférences',
    settings_meal_reminders: 'Rappels de Repas',
    settings_challenge_updates: 'Mises à Jour des Défis',
    settings_language: 'Langue',
    settings_greeting_color: 'Nom & Couleur de Salutation',
    settings_theme: 'Thème & Apparence',
    settings_dark_mode: 'Mode Sombre',
    settings_dark_desc: 'Thème sombre à fort contraste',
    settings_light_desc: 'Thème clair lumineux',
    settings_sustainability: 'Durabilité',
    settings_daily_goal: 'Objectif Déchets Quotidien',
    settings_campus_visibility: 'Visibilité Campus',
    settings_campus_visibility_desc: 'Afficher sur le classement BBS',
    settings_support: 'Assistance',
    settings_faq: 'Foire Aux Questions',
    settings_contact_us: 'Nous Contacter',
    settings_privacy: 'Politique de Confidentialité',
    settings_sign_out: 'Se Déconnecter',
    settings_sign_out_confirm: 'Êtes-vous sûr de vouloir vous déconnecter de BBS PIK EcoEat ?',

    // Modals
    modal_edit_profile: 'Modifier le Profil Élève',
    modal_choose_avatar: 'Choisir un Avatar',
    modal_profile_pic: 'Photo de Profil',
    modal_custom_photo_active: 'Photo Personnalisée Active',
    modal_upload_photo: 'Téléverser Photo',
    modal_take_photo: 'Prendre une Photo',
    modal_link: 'Lien',
    modal_photo_instructions: 'Téléversez une image personnelle (PNG, JPG, WebP) depuis votre appareil ou caméra.',
    modal_drag_drop: 'Glissez-déposez votre photo ici, ou parcourez les fichiers',
    modal_supports_formats: "Prend en charge tous les formats d'image jusqu'à 8 Mo",
    modal_apply_url: 'Appliquer URL',
    modal_hide_presets: '▼ Masquer les Avatars Exemples',
    modal_show_presets: '▶ Ou choisir un avatar exemple',
    modal_full_name: 'Nom Complet',
    modal_greeting_name: "Nom d'Accueil (Tableau de Bord)",
    modal_grade: 'Classe',
    modal_save_changes: 'Enregistrer les Modifications',
    modal_pw_title: 'Changer le Mot de Passe',
    modal_current_pw: 'Mot de Passe Actuel',
    modal_new_pw: 'Nouveau Mot de Passe',
    modal_update_pw: 'Mettre à Jour le Mot de Passe',
    modal_pw_updated_title: 'Mot de Passe Mis à Jour !',
    modal_pw_updated_desc: 'Vos identifiants scolaires ont été mis à jour en toute sécurité.',
    modal_greeting_accent_title: 'Couleur de Salutation',
    modal_greeting_accent_desc: 'Personnalisez la couleur du message de bienvenue sur votre tableau de bord.',
    modal_theme_title: 'Apparence & Thèmes',
    modal_theme_desc: "Personnalisez la palette de couleurs et l'ambiance visuelle.",
    modal_badge_gallery_title: 'Galerie des Badges du Campus',
    modal_special_title: 'Spécial Réfectoire du Campus',
    modal_close_special: 'Fermer le Spécial',
    modal_reward_milestone: 'Palier de Récompense',
    modal_rewards_list: "Récompenses de l'Établissement :",

    // Toasts
    toast_profile_updated: 'Profil mis à jour avec succès',
    toast_preferences_saved: 'Préférences enregistrées',
    toast_language_changed: 'Langue modifiée en',
    toast_greeting_updated: 'Couleur de salutation mise à jour !',
    toast_signed_out: 'Déconnexion réussie',
    toast_clean_verified: '✨ Assiette propre validée ! XP ajouté à votre classement !',
    toast_level_up: '🎉 Niveau supérieur ! Vous avez atteint le Niveau',
  },

  Mandarin: {
    // General / Common
    app_name: 'EcoEat',
    school_name: 'BBS PIK',
    save: '保存',
    cancel: '取消',
    done: '完成',
    close: '关闭',
    customizable: '可自定义',
    verified: '已认证',
    back: '返回',
    edit: '编辑',
    level: '等级',
    xp: '经验值',
    rank: '排名',
    streak: '连续天数',
    days: '天',
    days_left: '天剩余',
    students: '名学生',
    rewards: '奖励',
    view_details: '查看详情',
    view_all: '查看全部',
    awesome: '太棒了',
    active: '当前使用',
    change: '更换',

    // Navigation
    nav_dashboard: '首页',
    nav_capture: '扫描餐食',
    nav_leaderboard: '排行榜',
    nav_profile: '个人主页',
    nav_settings: '设置',
    nav_menu: '菜单',
    drawer_menu: '校园菜单',
    drawer_themes: '主题与外观',
    drawer_student_hub: 'BBS PIK 学生中心',

    // Dashboard
    greeting_morning: '早上好',
    greeting_afternoon: '下午好',
    greeting_evening: '晚上好',
    greeting_subtitle: '准备好今天通过午餐为校园环保贡献力量了吗？',
    stat_food_saved: '节约粮食',
    stat_saved_this_week: '本周节约',
    stat_level_title: '环保卫士等级',
    stat_xp_to_next: '距离下一级经验',
    stat_streak: '连续光盘天数',
    portion_title: '选择今日用餐分量',
    portion_small: '小份',
    portion_small_desc: '轻食 / 点心',
    portion_regular: '标准',
    portion_regular_desc: '普通食量',
    portion_large: '大份',
    portion_large_desc: '大食量餐食',
    btn_scan_meal: '扫描并记录餐食',
    btn_scan_meal_desc: 'AI 分量识别与光盘打卡',
    section_campus_challenge: '校园可持续挑战赛',
    challenge_title: '1 吨粮食减废目标',
    challenge_diverted_so_far: '公斤已减废',
    section_recent_meals: '最近用餐记录',
    meal_clean_plate: '光盘率',
    meal_co2_diverted: '减少碳排',
    section_daily_tips: '每日校园环保小贴士',
    section_campus_special: '今日餐厅特供',
    special_title: '有机鲜蔬农场沙拉',
    special_desc: '本地有机生菜、圣女果、黄瓜、烤鹰嘴豆与特调柠檬芝麻酱。',
    special_plant_rich: '100% 植物性营养',
    special_station: '取餐点：北二食堂',

    // Capture & Camera Viewfinder
    capture_title: 'AI 餐食扫描仪',
    capture_step_1: '1. 用餐前分量扫描',
    capture_step_2: '2. 光盘清洁验证',
    capture_align_meal: '将餐盘对准取景框以识别食材并估算分量',
    capture_align_plate: '将空盘对准取景框以进行光盘验证并领取经验奖励',
    capture_btn_snap: '拍照记录',
    capture_btn_retake: '重新拍摄',
    capture_analyzing: 'AI 智能分析中...',
    capture_dish_name: '识别菜品',
    capture_calories: '预估热量',
    capture_portion_weight: '预估分量',
    capture_ingredients: '识别食材',
    capture_carbon_diverted: '减少 CO2 排放',
    capture_clean_plate_conf: '光盘清洁度',
    capture_waste_grams: '剩余厨余',
    capture_xp_reward: '获得经验值',
    capture_btn_proceed: '确认无误，开始用餐！',
    capture_btn_finish: '验证光盘并完成',
    capture_bonus_awarded: '+20 经验值 光盘奖励已解锁！',
    capture_cancel: '取消扫描',
    capture_demo_sample: '尝试示例菜品',

    // Leaderboard
    lb_title: '校园排行榜',
    lb_tab_bbs: 'BBS PIK',
    lb_tab_goal: '校园目标',
    lb_tab_class: '年级班级',
    lb_top_champion: '当前第一名环保先锋',
    lb_student_rankings: '学生排行榜',
    lb_challenge_title: '校园 1 吨减废挑战',
    lb_challenge_sub: 'BBS PIK 校园可持续行动',
    lb_your_rank: '您的全校排名',
    lb_class_rankings: '各年级粮食减废量',

    // Profile
    profile_title: '学生环保档案',
    profile_edit_picture_hint: '点击更换头像',
    profile_edit_btn: '编辑个人信息',
    profile_summary: '环保成果汇总',
    profile_total_food_saved: '累计节约粮食',
    profile_streak_days: '连续打卡天数',
    profile_badges_unlocked: '已获徽章',
    profile_current_tier: '当前等级',
    profile_badges_heading: '环保荣誉徽章',
    profile_view_all_badges: '查看全部徽章',
    profile_meal_history: '用餐历史记录',

    // Settings
    settings_title: '设置',
    settings_account: '账户',
    settings_edit_profile: '编辑个人信息与头像',
    settings_change_password: '修改密码',
    settings_school_id: '学籍认证',
    settings_preferences: '应用偏好',
    settings_meal_reminders: '用餐打卡提醒',
    settings_challenge_updates: '挑战赛动态通知',
    settings_language: '语言设置 (Language)',
    settings_greeting_color: '问候昵称与高亮颜色',
    settings_theme: '主题与色彩外观',
    settings_dark_mode: '深色模式',
    settings_dark_desc: '高对比度深色护眼主题',
    settings_light_desc: '清新明亮日间主题',
    settings_sustainability: '可持续发展目标',
    settings_daily_goal: '每日厨余控制目标',
    settings_campus_visibility: '校园公开可见性',
    settings_campus_visibility_desc: '在 BBS PIK 排行榜上展示您的数据',
    settings_support: '帮助与支持',
    settings_faq: '常见问题 (FAQ)',
    settings_contact_us: '联系我们',
    settings_privacy: '隐私政策',
    settings_sign_out: '退出登录',
    settings_sign_out_confirm: '确定要退出 BBS PIK EcoEat 账号吗？',

    // Modals
    modal_edit_profile: '编辑学生个人信息',
    modal_choose_avatar: '选择头像',
    modal_profile_pic: '个人头像',
    modal_custom_photo_active: '已使用自定义照片',
    modal_upload_photo: '上传照片',
    modal_take_photo: '拍照上传',
    modal_link: '图片链接',
    modal_photo_instructions: '从设备上传您的照片 (PNG, JPG, WebP) 或直接拍照。',
    modal_drag_drop: '拖放照片到此处，或点击浏览文件',
    modal_supports_formats: '支持最大 8MB 的各类图片格式',
    modal_apply_url: '应用链接',
    modal_hide_presets: '▼ 隐藏预设头像',
    modal_show_presets: '▶ 或选择示例预设头像',
    modal_full_name: '展示全名',
    modal_greeting_name: '首页问候称呼',
    modal_grade: '年级',
    modal_save_changes: '保存更改',
    modal_pw_title: '修改密码',
    modal_current_pw: '当前密码',
    modal_new_pw: '新密码',
    modal_update_pw: '更新密码',
    modal_pw_updated_title: '密码修改成功！',
    modal_pw_updated_desc: '您的校园学生账号凭据已安全更新。',
    modal_greeting_accent_title: '问候语强调颜色',
    modal_greeting_accent_desc: '自定义 EcoEat 首页标题的称呼字体色彩。',
    modal_theme_title: '外观与色彩主题',
    modal_theme_desc: '个性化定制应用色彩氛围。',
    modal_badge_gallery_title: '校园荣誉徽章图鉴',
    modal_special_title: '校园餐厅今日特色',
    modal_close_special: '关闭特供详情',
    modal_reward_milestone: '奖励里程碑',
    modal_rewards_list: '全校社区奖励：',

    // Toasts
    toast_profile_updated: '个人信息更新成功',
    toast_preferences_saved: '偏好设置已保存',
    toast_language_changed: '语言已切换为',
    toast_greeting_updated: '问候语颜色已更新！',
    toast_signed_out: '已成功退出登录',
    toast_clean_verified: '✨ 光盘验证成功！经验值已计入全校排行榜！',
    toast_level_up: '🎉 升级啦！您已晋升至等级',
  },
};

interface LanguageContextType {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  t: (key: string, defaultText?: string) => string;
  supportedLanguages: LanguageOption[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{
  children: React.ReactNode;
  initialLanguage?: SupportedLanguage;
  onLanguageChange?: (lang: SupportedLanguage) => void;
}> = ({ children, initialLanguage = 'English', onLanguageChange }) => {
  const [language, setLanguageState] = useState<SupportedLanguage>(() => {
    const saved = localStorage.getItem('ecoeat_language') as SupportedLanguage;
    if (saved && translations[saved]) {
      return saved;
    }
    return initialLanguage;
  });

  useEffect(() => {
    localStorage.setItem('ecoeat_language', language);
    if (onLanguageChange) {
      onLanguageChange(language);
    }
  }, [language, onLanguageChange]);

  const setLanguage = (newLang: SupportedLanguage) => {
    if (translations[newLang]) {
      setLanguageState(newLang);
    }
  };

  const t = (key: string, defaultText?: string): string => {
    const langDict = translations[language] || translations.English;
    if (langDict[key]) {
      return langDict[key];
    }
    // Fallback to English
    if (translations.English[key]) {
      return translations.English[key];
    }
    return defaultText || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
        supportedLanguages: SUPPORTED_LANGUAGES,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
