import React, { createContext, useContext, useEffect, useState } from 'react';
import { additionalTranslations } from '../data/translationsExtension';
import { foodTranslationsByLanguage } from '../data/foodTranslations';

export type SupportedLanguage = 'English' | 'Bahasa Indonesia' | 'Spanish' | 'French' | 'Mandarin';

export interface LanguageOption {
  code: string;
  name: SupportedLanguage;
  nativeName: string;
  flag: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'id', name: 'Bahasa Indonesia', nativeName: 'Bahasa Indonesia', flag: '🇮🇩' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'zh', name: 'Mandarin', nativeName: '中文 (简体)', flag: '🇨🇳' },
];

export const translations: Record<SupportedLanguage, Record<string, string>> = {
  English: {
    // General / Common
    app_name: 'EcoEat',
    school_name: 'BBS PIK',
    save: 'Save',
    cancel: 'Cancel',
    done: 'Done',
    close: 'Close',
    customizable: 'Customizable',
    verified: 'Verified',
    back: 'Back',
    edit: 'Edit',
    level: 'Level',
    xp: 'XP',
    rank: 'Rank',
    streak: 'Streak',
    days: 'Days',
    days_left: 'days left',
    students: 'Students',
    rewards: 'Rewards',
    view_details: 'View Details',
    view_all: 'View All',
    awesome: 'Awesome',
    active: 'Active',
    change: 'Change',

    // Navigation
    nav_dashboard: 'Dashboard',
    nav_capture: 'Scan Meal',
    nav_leaderboard: 'Leaderboard',
    nav_shop: 'Sticker Shop',
    nav_profile: 'Profile',
    nav_settings: 'Settings',
    nav_menu: 'Menu',
    drawer_menu: 'Campus Menu',
    drawer_themes: 'Theme & Appearance',
    drawer_student_hub: 'BBS PIK Student Hub',

    // Dashboard
    greeting_morning: 'Good morning',
    greeting_afternoon: 'Good afternoon',
    greeting_evening: 'Good evening',
    greeting_subtitle: 'Ready to turn lunch into campus eco-impact today?',
    stat_food_saved: 'Food Saved',
    stat_saved_this_week: 'Saved this week',
    stat_level_title: 'Eco Warrior Level',
    stat_xp_to_next: 'XP to Level',
    stat_streak: 'Day Streak',
    portion_title: "Select Today's Dining Portion",
    portion_small: 'Small',
    portion_small_desc: 'Light bite / snack',
    portion_regular: 'Regular',
    portion_regular_desc: 'Standard hunger',
    portion_large: 'Large',
    portion_large_desc: 'Heavy meal',
    btn_scan_meal: 'Scan & Log Meal',
    btn_scan_meal_desc: 'AI portion recognition & clean plate scan',
    section_campus_challenge: 'Campus Sustainability Challenge',
    challenge_title: '1-Ton Food Divert Goal',
    challenge_diverted_so_far: 'kg diverted so far',
    section_recent_meals: 'Recent Meals Log',
    meal_clean_plate: 'Clean Plate',
    meal_co2_diverted: 'CO2 Diverted',
    section_daily_tips: 'Daily Campus Eco Tips',
    section_campus_special: "Today's Dining Hall Special",
    special_title: 'Farm-Fresh Organic Garden Salad',
    special_desc: 'Locally harvested organic crisp lettuce, cherry tomatoes, cucumbers, toasted chickpeas, and house-made lemon tahini vinaigrette.',
    special_plant_rich: '100% Plant-Rich',
    special_station: 'Station: Dining Hall North 2',

    // Capture & Camera Viewfinder
    capture_title: 'AI Meal Scanner',
    capture_step_1: '1. Food Selection & Portion',
    capture_step_2: '2. AI Meal Scan',
    capture_step_3: '3. Clean Plate Verification',
    capture_step_choose_food: '1. Food Category & Meal',
    capture_step_scan_meal: '2. AI Meal Scan',
    capture_step_clean_plate: '3. Clean Plate Verification',
    question_food_category: 'What food category are you going to eat?',
    question_food_item: 'What food are you going to eat from that category?',
    popular_options: 'Popular Dining Dishes',
    custom_dish_placeholder: 'Or type custom dish name...',
    continue_to_scan: 'Continue to Scan Plate',
    change_food: 'Change Food',
    dining_on: 'Dining on',
    capture_align_meal: 'Align meal within frame to identify items and estimate portion',
    capture_align_plate: 'Align empty plate to verify clean plate & award bonus XP',
    capture_btn_snap: 'Capture Photo',
    capture_btn_retake: 'Retake Photo',
    capture_analyzing: 'Analyzing with AI...',
    capture_dish_name: 'Recognized Dish',
    capture_calories: 'Est. Calories',
    capture_portion_weight: 'Est. Portion Weight',
    capture_ingredients: 'Identified Ingredients',
    capture_carbon_diverted: 'CO2 Emissions Diverted',
    capture_clean_plate_conf: 'Clean Plate Confidence',
    capture_waste_grams: 'Remaining Waste',
    capture_xp_reward: 'XP Earned',
    capture_btn_proceed: 'Looks Good, Enjoy Meal!',
    capture_btn_finish: 'Verify Clean Plate & Finish',
    capture_bonus_awarded: '+20 XP Clean Plate Bonus Unlocked!',
    capture_cancel: 'Cancel Scan',

    // Leaderboard
    lb_title: 'Campus Leaderboard',
    lb_tab_bbs: 'BBS PIK',
    lb_tab_goal: 'Campus Goal',
    lb_tab_class: 'Grade Classes',
    lb_top_champion: 'Current #1 Eco Warrior',
    lb_student_rankings: 'Student Rankings',
    lb_challenge_title: 'Campus 1-Ton Food Divert',
    lb_challenge_sub: 'BBS PIK Campus Sustainability Challenge',
    lb_your_rank: 'Your Campus Rank',
    lb_class_rankings: 'Grade Level Waste Diverted',

    // Profile
    profile_title: 'Student Eco Profile',
    profile_edit_picture_hint: 'Click to change photo',
    profile_edit_btn: 'Edit Profile',
    profile_summary: 'Sustainability Summary',
    profile_total_food_saved: 'Total Food Saved',
    profile_streak_days: 'Daily Streak',
    profile_badges_unlocked: 'Badges Earned',
    profile_current_tier: 'Current Tier',
    profile_badges_heading: 'Eco Badges',
    profile_view_all_badges: 'View All Badges',
    profile_meal_history: 'Meal History Log',

    // Settings
    settings_title: 'Settings',
    settings_account: 'Account',
    settings_edit_profile: 'Edit Profile & Picture',
    settings_change_password: 'Change Password',
    settings_school_id: 'School ID',
    settings_preferences: 'Preferences',
    settings_meal_reminders: 'Meal Reminders',
    settings_challenge_updates: 'Challenge Updates',
    settings_language: 'Language',
    settings_greeting_color: 'Greeting Name & Color',
    settings_theme: 'Theme & Appearance',
    settings_dark_mode: 'Dark Mode',
    settings_dark_desc: 'High contrast dark theme',
    settings_light_desc: 'Crisp daylight theme',
    settings_sustainability: 'Sustainability',
    settings_daily_goal: 'Daily Food Saved',
    settings_campus_visibility: 'Campus Visibility',
    settings_campus_visibility_desc: 'Participate in BBS Campus Challenges',
    settings_support: 'Support',
    settings_faq: 'FAQ',
    settings_contact_us: 'Contact Us',
    settings_privacy: 'Privacy Policy',
    settings_sign_out: 'Sign Out',
    settings_sign_out_confirm: 'Are you sure you want to sign out of BBS PIK EcoEat?',

    // Modals
    modal_edit_profile: 'Edit Student Profile',
    modal_choose_avatar: 'Choose Avatar',
    modal_profile_pic: 'Profile Picture',
    modal_custom_photo_active: 'Custom Photo Active',
    modal_upload_photo: 'Upload Photo',
    modal_take_photo: 'Take Photo',
    modal_link: 'Link',
    modal_photo_instructions: 'Upload any personal image (PNG, JPG, WebP) from your device or camera.',
    modal_drag_drop: 'Drag & drop your picture here, or browse file',
    modal_supports_formats: 'Supports all image formats up to 8MB',
    modal_apply_url: 'Apply URL',
    modal_hide_presets: '▼ Hide Avatar Presets',
    modal_show_presets: '▶ Or choose a sample avatar preset',
    modal_full_name: 'Full Display Name',
    modal_greeting_name: 'Greeting Name (Dashboard)',
    modal_grade: 'Grade',
    modal_save_changes: 'Save Changes',
    modal_pw_title: 'Change Password',
    modal_current_pw: 'Current Password',
    modal_new_pw: 'New Password',
    modal_update_pw: 'Update Password',
    modal_pw_updated_title: 'Password Updated!',
    modal_pw_updated_desc: 'Your campus student credentials have been securely updated.',
    modal_greeting_accent_title: 'Greeting Accent Color',
    modal_greeting_accent_desc: 'Personalize the header greeting text style on your EcoEat dashboard.',
    modal_theme_title: 'Appearance & Themes',
    modal_theme_desc: 'Personalize the application color palette and visual atmosphere.',
    modal_badge_gallery_title: 'Campus Badges Gallery',
    modal_special_title: 'Campus Meal Hall Special',
    modal_close_special: 'Close Special',
    modal_reward_milestone: 'Reward Milestone',
    modal_rewards_list: 'School Community Rewards:',

    // Toasts
    toast_profile_updated: 'Profile updated successfully',
    toast_preferences_saved: 'Preferences saved',
    toast_language_changed: 'Language switched to',
    toast_greeting_updated: 'Greeting color updated!',
    toast_signed_out: 'Signed out successfully',
    toast_clean_verified: '✨ Clean plate verified! XP added to your campus ranking!',
    toast_level_up: '🎉 Level Up! You reached Level',

    // Authentication & Log-in Page
    auth_header_subtitle: 'Campus Sustainability & Nutrition Hub',
    auth_select_language: 'Select Language',
    auth_pitch_badge: 'Official Campus Dining & Zero Waste Hub',
    auth_pitch_title_1: 'Turn Every Meal into',
    auth_pitch_title_2: 'Campus Eco-Impact',
    auth_pitch_desc: 'Scan your dining plate, minimize food waste, earn XP for your grade, and help BBS PIK achieve its 1,000kg zero-waste semester goal.',
    auth_active_students: 'Active Students',
    auth_food_diverted: 'Food Diverted',
    auth_feature_sso: 'Single Sign-On with BBS PIK Student ID & Email',
    auth_feature_ai: 'AI Vision camera for automated portion and clean-plate tracking',
    auth_feature_rankings: 'Real-time Inter-Grade Rankings & Campus Dining Credits',
    auth_tab_signin: 'Student Sign In',
    auth_tab_signup: 'Create Account',
    auth_verification_title: 'Account Verification:',
    auth_verification_desc: '1 official account per BBS PIK student. Account copying or duplicate registration is prohibited.',
    auth_label_email_or_id: 'BBS PIK Student Email or ID',
    auth_placeholder_email_or_id: 'e.g. student.name@bbs-pik.edu',
    auth_label_password: 'Password',
    auth_forgot_password: 'Forgot?',
    auth_remember_me: 'Remember my student login',
    auth_btn_signin: 'Sign In to Campus Hub',
    auth_new_to_ecoeat: 'New to BBS PIK EcoEat?',
    auth_link_create_account: 'Create Student Account',
    auth_label_fullname: 'Full Student Name',
    auth_placeholder_fullname: 'e.g. Maya Lin',
    auth_label_grade: 'Grade',
    auth_label_section: 'Section / Homeroom',
    auth_section_a: 'Section A',
    auth_section_b: 'Section B',
    auth_section_c: 'Section C',
    auth_section_d: 'Section D',
    auth_label_school_email: 'School Email',
    auth_placeholder_school_email: 'student@bbs-pik.edu',
    auth_label_create_password: 'Create Password',
    auth_placeholder_password_len: 'At least 6 characters',
    auth_btn_signup: 'Join Campus Eco Program (+50 XP)',
    auth_terms_agreement: 'By registering, you agree to the',
    auth_sustainability_charter: 'Sustainability Charter',
    auth_and: 'and',
    auth_terms_of_service: 'Terms of Service',
    auth_already_have_account: 'Already have an account?',
    auth_link_signin: 'Sign In',
    auth_reset_pw_title: 'Reset Student Password',
    auth_reset_pw_desc: 'Enter your registered BBS PIK student email address. We will send a secure one-time reset code to your school inbox.',
    auth_btn_send_reset: 'Send Reset Link',
    auth_reset_sent_title: 'Password Reset Link Dispatched!',
    auth_reset_sent_desc_prefix: 'We sent instructions to',
    auth_reset_sent_desc_suffix: '. Follow the campus link to choose a new password.',
    auth_btn_return_signin: 'Return to Sign In',
    auth_hide_password: 'Hide password',
    auth_show_password: 'Show password',
    auth_footer_bbs: 'Bina Bangsa School',
    auth_footer_pik: 'PIK Campus',
    auth_footer_tagline: 'BBS PIK EcoEat • Campus Sustainability & Food Waste Diversion Program 2026',
    auth_err_email_id_required: 'Please enter your BBS PIK Student Email or Student ID',
    auth_err_password_required: 'Please enter your account password',
    auth_err_failed: 'Failed to authenticate. Please check your credentials.',
    auth_err_name_required: 'Please provide your full student name',
    auth_err_email_required: 'Please provide a valid BBS PIK student email',
    auth_err_email_invalid: 'Please provide a valid BBS PIK email (e.g. name@bbs-pik.edu)',
    auth_err_password_short: 'Password should be at least 6 characters',
    auth_success_signup: 'Student account created successfully! Signing in...',
    auth_err_registration_failed: 'Account registration failed. Copying existing student accounts is prohibited.',

    // Comprehensive UI Keys
    step: 'Step',
    of: 'of',
    clean_plate_bonus_hint: 'Smart vision verifies food items, nutrition macros, and CO2 diversion.',
    finished_fruit_verified: 'Finished Fruit 100% Verified',
    clean_plate_verified: 'Clean Plate 100% Verified',
    finished_fruit_title: 'All Fruit Eaten • Peels Composted',
    zero_waste_achieved: 'Zero Waste Achieved',
    clean_plate_praise: 'Outstanding eco action!',
    welcome_back: 'Welcome back,',
    tagline: 'Eat Smart. Save More. Go Green.',
    current_streak: 'Current Streak',
    view_weekly_impact_tooltip: 'Click to view Weekly Impact breakdown',
    food_saved: 'Food Saved',
    eco_diversion_metric: 'Eco diversion metric',
    kg: 'kg',
    kg_this_week: 'kg this week',
    view_weekly_impact_action: 'Weekly Impact',
    current_level: 'Current Level',
    xp_milestone_rank: 'XP milestone rank',
    dashboard_sticker_shop_title: 'Campus Eco Sticker Store',
    dashboard_sticker_shop_desc: 'Collect from 1,000 campus eco stickers & badges with your zero-waste clean plate XP!',
    of_campus_goal: 'Diverted',
    start_new_meal: 'Start New Meal',
    daily_tips: 'Daily Eco Tips',
    recent_meals: 'Recent Meals',
    restart: 'Restart',
    unlocked: 'Unlocked',
    profile_stickers_title: 'Campus Eco Stickers',
    profile_stickers_desc: 'Purchased with clean dining & zero food waste XP',
    profile_btn_visit_shop: 'Sticker Store',
    profile_no_stickers_title: 'No Stickers in Your Collection Yet',
    profile_no_stickers_desc: 'Exchange your clean plate dining XP for cool BBS campus stickers in the Sticker Shop!',
    profile_btn_browse_stickers: 'Browse Sticker Shop',
    weekly_impact: 'Weekly Impact',
    weekly_impact_desc: 'Campus food diversion & clean plate tracking by weekday',
    total_saved: 'Total Saved',
    settings_language_desc: 'Choose interface language',
    customize: 'Customize',
    settings_data_history: 'Data & Meals',
    restart_recent_meals: 'Restart Recent Meals Log',
    restart_recent_meals_desc: 'Clear past meal scans and start fresh from 0 meals',
    shop_cat_all: 'All Stickers',
    shop_cat_clean_plate: '🍽️ Clean Plate',
    shop_cat_campus_pride: '🏫 BBS Campus',
    shop_cat_zero_waste: '♻️ Zero Waste',
    shop_cat_nature_planet: '🌍 Planet & Ocean',
    shop_cat_culinary: '🥗 Culinary',
    sticker_rarity_common: 'Common',
    sticker_rarity_rare: 'Rare',
    sticker_rarity_epic: 'Epic',
    sticker_rarity_legendary: 'Legendary',
    shop_badge_tag: 'BBS PIK Campus Eco Rewards',
    shop_title: 'Campus Eco Sticker Shop',
    shop_subtitle: 'Exchange the XP you earned by finishing your food and returning clean dining plates for official campus eco stickers. Collect across 1,000,000 procedural editions in 5 categories and showcase your zero-waste pride!',
    shop_earn_tip: 'Clean your plate to earn +25 to +50 XP per meal!',
    shop_spendable_balance: 'Spendable XP Balance',
    shop_safe_rank: 'Lifetime Rank Safe',
    shop_stickers_owned: 'Collected',
    shop_btn_scan_for_xp: 'Scan Meal to Earn More XP',
    shop_tab_store: 'Sticker Store',
    shop_tab_album: 'My Sticker Album',
    shop_search_placeholder: 'Search 1,000,000 stickers, #ID, or keyword (e.g. #777777, Tiger, Dragon)...',
    shop_rarity_filter: 'Rarity:',
    shop_showing_count: 'Showing',
    shop_collected_label: 'collected stickers',
    shop_stickers_label: 'stickers',
    shop_album_empty_title: 'No stickers in your album yet!',
    shop_no_stickers_found: 'No stickers match your filter',
    shop_album_empty_desc: 'Browse the Sticker Store to purchase your first eco sticker with your dining XP!',
    shop_try_other_filter: 'Try clearing your search query or selecting a different category.',
    shop_btn_browse_store: 'Browse Sticker Store',
    shop_equipped_badge: 'Equipped',
    shop_click_to_inspect: 'Inspect & Download',
    shop_btn_unequip: 'Unequip',
    shop_btn_equip_showcase: 'Equip Showcase',
    shop_download_hint: 'Download Sticker PNG',
    shop_btn_buy: 'Buy Sticker',
    shop_need_more_prefix: 'Need',
    theme_modal_title: 'App Themes & Appearance',
    theme_modal_subtitle: 'Customize campus visual styles and display mode',
    display_mode_heading: 'Display Mode',
    dark_mode_title: 'Dark Mode',
    dark_mode_desc: 'Deep contrast, battery saving',
    light_mode_title: 'Light Mode',
    light_mode_desc: 'Clean day layout',
    color_palette_heading: 'Color Palette & Identity',
    btn_done_apply: 'Done & Apply Appearance',
    question_food_category_desc: 'Select your food category to calibrate AI recognition accuracy and nutritional metrics.',
    question_food_item_desc: 'Select a popular dish or search below',
    search_dish_placeholder: 'Search popular meals or type custom dish...',
    portion_size_heading: 'Portion Size',
    btn_proceed_camera: 'Proceed to Meal Scan',
    btn_verify_clean_plate: 'Verify Clean Plate & Claim XP',
    toast_meals_restarted: '✨ Recent meals log has been restarted to 0!',
    toast_signed_out_bbs: 'Signed out of BBS PIK EcoEat',
    toast_challenge_joined: '🎉 Joined campus sustainability challenge!',
    planned_portion_size: 'Planned Portion Size',
    selected_dining_profile: 'Selected Dining Profile',
    portion: 'Portion',
    options_available: 'Options Available',
    clear: 'Clear',
    search: 'Search',
    snapshot_captured: 'Snapshot Captured',
    starting_camera: 'Starting AI Camera Viewfinder...',
    camera_ready: 'Camera Ready for Scanning',
    connecting_camera: 'Connecting to your camera feed...',
    point_at_food: 'Point at your food and tap the round button, or take a photo directly.',
    take_photo_directly: 'Take Photo Directly',
    retry_live: 'Retry Live',
    starting_camera_dots: 'Starting Camera...',
    active_snapshot: 'Active Snapshot',
    align_clean_plate: 'Align Clean Plate',
    center_food_frame: 'Center Food or Produce in Frame',
  },

  'Bahasa Indonesia': {
    // General / Common
    app_name: 'EcoEat',
    school_name: 'BBS PIK',
    save: 'Simpan',
    cancel: 'Batal',
    done: 'Selesai',
    close: 'Tutup',
    customizable: 'Dapat Disesuaikan',
    verified: 'Terverifikasi',
    back: 'Kembali',
    edit: 'Ubah',
    level: 'Tingkat',
    xp: 'XP',
    rank: 'Peringkat',
    streak: 'Runtunan',
    days: 'Hari',
    days_left: 'hari tersisa',
    students: 'Siswa',
    rewards: 'Hadiah',
    view_details: 'Lihat Detail',
    view_all: 'Lihat Semua',
    awesome: 'Keren',
    active: 'Aktif',
    change: 'Ubah',

    // Navigation
    nav_dashboard: 'Beranda',
    nav_capture: 'Pindai Makanan',
    nav_leaderboard: 'Papan Peringkat',
    nav_shop: 'Toko Stiker',
    nav_profile: 'Profil',
    nav_settings: 'Pengaturan',
    nav_menu: 'Menu',
    drawer_menu: 'Menu Kampus',
    drawer_themes: 'Tema & Tampilan',
    drawer_student_hub: 'Pusat Siswa BBS PIK',

    // Dashboard
    greeting_morning: 'Selamat pagi',
    greeting_afternoon: 'Selamat siang',
    greeting_evening: 'Selamat malam',
    greeting_subtitle: 'Siap mengubah makan siang menjadi dampak ramah lingkungan hari ini?',
    stat_food_saved: 'Makanan Diselamatkan',
    stat_saved_this_week: 'Diselamatkan minggu ini',
    stat_level_title: 'Tingkat Pejuang Lingkungan',
    stat_xp_to_next: 'XP menuju Tingkat',
    stat_streak: 'Hari Berturut-turut',
    portion_title: 'Pilih Porsi Makan Hari Ini',
    portion_small: 'Kecil',
    portion_small_desc: 'Camilan ringan',
    portion_regular: 'Biasa',
    portion_regular_desc: 'Porsi standar',
    portion_large: 'Besar',
    portion_large_desc: 'Porsi kenyang',
    btn_scan_meal: 'Pindai & Catat Makanan',
    btn_scan_meal_desc: 'Pengenalan porsi AI & piring bersih',
    section_campus_challenge: 'Tantangan Keberlanjutan Kampus',
    challenge_title: 'Target Pengurangan 1 Ton Makanan',
    challenge_diverted_so_far: 'kg dikurangi sejauh ini',
    section_recent_meals: 'Riwayat Makanan Terkini',
    meal_clean_plate: 'Piring Bersih',
    meal_co2_diverted: 'CO2 Dikurangi',
    section_daily_tips: 'Tips Ramah Lingkungan Harian',
    section_campus_special: 'Spesial Kantin Kampus Hari Ini',
    special_title: 'Salad Segar Organik Kebun',
    special_desc: 'Selada renyah organik lokal, tomat ceri, mentimun, buncis panggang, dan saus tahini lemon segar.',
    special_plant_rich: '100% Kaya Nabati',
    special_station: 'Lokasi: Kantin Utara 2',

    // Capture & Camera Viewfinder
    capture_title: 'Pemindai Makanan AI',
    capture_step_1: '1. Pilihan Makanan & Porsi',
    capture_step_2: '2. Pemindaian Makanan AI',
    capture_step_3: '3. Verifikasi Piring Bersih',
    capture_step_choose_food: '1. Kategori & Makanan',
    capture_step_scan_meal: '2. Pemindaian Makanan AI',
    capture_step_clean_plate: '3. Verifikasi Piring Bersih',
    question_food_category: 'Kategori makanan apa yang akan Anda santap?',
    question_food_item: 'Makanan apa yang akan Anda santap dari kategori tersebut?',
    popular_options: 'Pilihan Populer Kantin',
    custom_dish_placeholder: 'Atau ketik nama makanan sendiri...',
    continue_to_scan: 'Lanjut Memindai Piring',
    change_food: 'Ganti Makanan',
    dining_on: 'Menyantap',
    capture_align_meal: 'Arahkan makanan ke dalam bingkai untuk mengenali porsi',
    capture_align_plate: 'Arahkan piring kosong untuk verifikasi piring bersih & klaim bonus XP',
    capture_btn_snap: 'Ambil Foto',
    capture_btn_retake: 'Foto Ulang',
    capture_analyzing: 'Menganalisis dengan AI...',
    capture_dish_name: 'Makanan Terdeteksi',
    capture_calories: 'Perkiraan Kalori',
    capture_portion_weight: 'Perkiraan Berat Porsi',
    capture_ingredients: 'Bahan yang Teridentifikasi',
    capture_carbon_diverted: 'Emisi CO2 Berhasil Dikurangi',
    capture_clean_plate_conf: 'Tingkat Kebersihan Piring',
    capture_waste_grams: 'Sisa Makanan',
    capture_xp_reward: 'XP Didapatkan',
    capture_btn_proceed: 'Sesuai, Selamat Menikmati!',
    capture_btn_finish: 'Verifikasi Piring Bersih & Selesai',
    capture_bonus_awarded: '+20 XP Bonus Piring Bersih Terbuka!',
    capture_cancel: 'Batalkan Pemindaian',

    // Leaderboard
    lb_title: 'Papan Peringkat Kampus',
    lb_tab_bbs: 'BBS PIK',
    lb_tab_goal: 'Target Kampus',
    lb_tab_class: 'Tingkat Kelas',
    lb_top_champion: 'Pejuang Lingkungan #1 Saat Ini',
    lb_student_rankings: 'Peringkat Siswa',
    lb_challenge_title: 'Target Pengurangan 1 Ton Makanan',
    lb_challenge_sub: 'Tantangan Keberlanjutan BBS PIK',
    lb_your_rank: 'Peringkat Kampus Anda',
    lb_class_rankings: 'Sampah Makanan Dikurangi per Tingkat',

    // Profile
    profile_title: 'Profil Siswa Eco',
    profile_edit_picture_hint: 'Klik untuk mengganti foto',
    profile_edit_btn: 'Ubah Profil',
    profile_summary: 'Ringkasan Keberlanjutan',
    profile_total_food_saved: 'Total Makanan Diselamatkan',
    profile_streak_days: 'Runtunan Harian',
    profile_badges_unlocked: 'Lencana Diraih',
    profile_current_tier: 'Tingkat Saat Ini',
    profile_badges_heading: 'Lencana Ramah Lingkungan',
    profile_view_all_badges: 'Lihat Semua Lencana',
    profile_meal_history: 'Riwayat Catatan Makanan',

    // Settings
    settings_title: 'Pengaturan',
    settings_account: 'Akun',
    settings_edit_profile: 'Ubah Profil & Foto',
    settings_change_password: 'Ubah Kata Sandi',
    settings_school_id: 'ID Sekolah',
    settings_preferences: 'Preferensi',
    settings_meal_reminders: 'Pengingat Makan',
    settings_challenge_updates: 'Pembaruan Tantangan',
    settings_language: 'Bahasa',
    settings_greeting_color: 'Nama & Warna Sapaan',
    settings_theme: 'Tema & Tampilan',
    settings_dark_mode: 'Mode Gelap',
    settings_dark_desc: 'Tema gelap kontras tinggi',
    settings_light_desc: 'Tema terang bersih',
    settings_sustainability: 'Keberlanjutan',
    settings_daily_goal: 'Target Makanan Terselamatkan Harian',
    settings_campus_visibility: 'Visibilitas Kampus',
    settings_campus_visibility_desc: 'Berpartisipasi dalam Tantangan Kampus BBS',
    settings_support: 'Bantuan',
    settings_faq: 'Tanya Jawab (FAQ)',
    settings_contact_us: 'Hubungi Kami',
    settings_privacy: 'Kebijakan Privasi',
    settings_sign_out: 'Keluar',
    settings_sign_out_confirm: 'Apakah Anda yakin ingin keluar dari BBS PIK EcoEat?',

    // Modals
    modal_edit_profile: 'Ubah Profil Siswa',
    modal_choose_avatar: 'Pilih Avatar',
    modal_profile_pic: 'Foto Profil',
    modal_custom_photo_active: 'Foto Khusus Aktif',
    modal_upload_photo: 'Unggah Foto',
    modal_take_photo: 'Ambil Foto',
    modal_link: 'Tautan',
    modal_photo_instructions: 'Unggah foto pribadi (PNG, JPG, WebP) dari perangkat atau kamera Anda.',
    modal_drag_drop: 'Tarik & lepas foto Anda di sini, atau cari berkas',
    modal_supports_formats: 'Mendukung semua format gambar hingga 8MB',
    modal_apply_url: 'Terapkan URL',
    modal_hide_presets: '▼ Sembunyikan Avatar Contoh',
    modal_show_presets: '▶ Atau pilih avatar contoh',
    modal_full_name: 'Nama Lengkap',
    modal_greeting_name: 'Nama Sapaan (Beranda)',
    modal_grade: 'Kelas',
    modal_save_changes: 'Simpan Perubahan',
    modal_pw_title: 'Ubah Kata Sandi',
    modal_current_pw: 'Kata Sandi Saat Ini',
    modal_new_pw: 'Kata Sandi Baru',
    modal_update_pw: 'Perbarui Kata Sandi',
    modal_pw_updated_title: 'Kata Sandi Diperbarui!',
    modal_pw_updated_desc: 'Kredensial siswa kampus Anda telah berhasil diperbarui.',
    modal_greeting_accent_title: 'Warna Aksen Sapaan',
    modal_greeting_accent_desc: 'Sesuaikan gaya warna teks sapaan pada beranda EcoEat Anda.',
    modal_theme_title: 'Tampilan & Tema',
    modal_theme_desc: 'Sesuaikan palet warna aplikasi dan atmosfer visual.',
    modal_badge_gallery_title: 'Galeri Lencana Kampus',
    modal_special_title: 'Spesial Kantin Kampus',
    modal_close_special: 'Tutup Spesial',
    modal_reward_milestone: 'Target Hadiah',
    modal_rewards_list: 'Hadiah Komunitas Sekolah:',

    // Toasts
    toast_profile_updated: 'Profil berhasil diperbarui',
    toast_preferences_saved: 'Preferensi disimpan',
    toast_language_changed: 'Bahasa diubah ke',
    toast_greeting_updated: 'Warna sapaan diperbarui!',
    toast_signed_out: 'Berhasil keluar',
    toast_clean_verified: '✨ Piring bersih terverifikasi! XP ditambahkan ke peringkat kampus!',
    toast_level_up: '🎉 Naik Tingkat! Anda mencapai Tingkat',

    // Authentication & Log-in Page
    auth_header_subtitle: 'Pusat Keberlanjutan & Nutrisi Kampus',
    auth_select_language: 'Pilih Bahasa',
    auth_pitch_badge: 'Pusat Resmi Kantin Kampus & Nol Sampah',
    auth_pitch_title_1: 'Ubah Setiap Makanan Menjadi',
    auth_pitch_title_2: 'Dampak Ramah Lingkungan Kampus',
    auth_pitch_desc: 'Pindai piring makan Anda, kurangi sampah makanan, dapatkan XP untuk kelas Anda, dan bantu BBS PIK mencapai target 1.000 kg bebas sampah semester ini.',
    auth_active_students: 'Siswa Aktif',
    auth_food_diverted: 'Makanan Diselamatkan',
    auth_feature_sso: 'Masuk Tunggal dengan ID Siswa & Email BBS PIK',
    auth_feature_ai: 'Kamera AI Vision untuk pelacakan porsi dan piring bersih otomatis',
    auth_feature_rankings: 'Peringkat Antar-Tingkat Waktu Nyata & Kredit Kantin Kampus',
    auth_tab_signin: 'Masuk Siswa',
    auth_tab_signup: 'Daftar Akun',
    auth_verification_title: 'Verifikasi Akun:',
    auth_verification_desc: '1 akun resmi per siswa BBS PIK. Penggandaan akun atau pendaftaran duplikat dilarang.',
    auth_label_email_or_id: 'Email Siswa atau ID BBS PIK',
    auth_placeholder_email_or_id: 'contoh: student.name@bbs-pik.edu',
    auth_label_password: 'Kata Sandi',
    auth_forgot_password: 'Lupa?',
    auth_remember_me: 'Ingat info masuk saya',
    auth_btn_signin: 'Masuk ke Pusat Kampus',
    auth_new_to_ecoeat: 'Baru di BBS PIK EcoEat?',
    auth_link_create_account: 'Buat Akun Siswa',
    auth_label_fullname: 'Nama Lengkap Siswa',
    auth_placeholder_fullname: 'contoh: Maya Lin',
    auth_label_grade: 'Tingkat Kelas',
    auth_label_section: 'Bagian / Kelas Wali',
    auth_section_a: 'Bagian A',
    auth_section_b: 'Bagian B',
    auth_section_c: 'Bagian C',
    auth_section_d: 'Bagian D',
    auth_label_school_email: 'Email Sekolah',
    auth_placeholder_school_email: 'student@bbs-pik.edu',
    auth_label_create_password: 'Buat Kata Sandi',
    auth_placeholder_password_len: 'Minimal 6 karakter',
    auth_btn_signup: 'Gabung Program Eco Kampus (+50 XP)',
    auth_terms_agreement: 'Dengan mendaftar, Anda menyetujui',
    auth_sustainability_charter: 'Piagam Keberlanjutan',
    auth_and: 'dan',
    auth_terms_of_service: 'Ketentuan Layanan',
    auth_already_have_account: 'Sudah memiliki akun?',
    auth_link_signin: 'Masuk',
    auth_reset_pw_title: 'Atur Ulang Kata Sandi Siswa',
    auth_reset_pw_desc: 'Masukkan alamat email siswa BBS PIK terdaftar Anda. Kami akan mengirimkan kode reset aman ke kotak masuk sekolah Anda.',
    auth_btn_send_reset: 'Kirim Tautan Reset',
    auth_reset_sent_title: 'Tautan Reset Kata Sandi Terkirim!',
    auth_reset_sent_desc_prefix: 'Kami telah mengirimkan petunjuk ke',
    auth_reset_sent_desc_suffix: '. Ikuti tautan kampus untuk memilih kata sandi baru.',
    auth_btn_return_signin: 'Kembali ke Halaman Masuk',
    auth_hide_password: 'Sembunyikan kata sandi',
    auth_show_password: 'Tampilkan kata sandi',
    auth_footer_bbs: 'Bina Bangsa School',
    auth_footer_pik: 'Kampus PIK',
    auth_footer_tagline: 'BBS PIK EcoEat • Program Keberlanjutan Kampus & Pengurangan Sampah Makanan 2026',
    auth_err_email_id_required: 'Harap masukkan Email Siswa atau ID Siswa BBS PIK Anda',
    auth_err_password_required: 'Harap masukkan kata sandi akun Anda',
    auth_err_failed: 'Gagal mengautentikasi. Silakan periksa kredensial Anda.',
    auth_err_name_required: 'Harap masukkan nama lengkap siswa Anda',
    auth_err_email_required: 'Harap masukkan email siswa BBS PIK yang valid',
    auth_err_email_invalid: 'Harap masukkan email BBS PIK yang valid (contoh: name@bbs-pik.edu)',
    auth_err_password_short: 'Kata sandi harus terdiri dari minimal 6 karakter',
    auth_success_signup: 'Akun siswa berhasil dibuat! Sedang masuk...',
    auth_err_registration_failed: 'Pendaftaran akun gagal. Penggandaan akun siswa yang ada dilarang.',

    // Comprehensive UI Keys
    step: 'Langkah',
    of: 'dari',
    clean_plate_bonus_hint: 'Visi cerdas memverifikasi makanan, makro nutrisi, dan pengurangan CO2.',
    finished_fruit_verified: 'Buah Habis 100% Terverifikasi',
    clean_plate_verified: 'Piring Bersih 100% Terverifikasi',
    finished_fruit_title: 'Semua Buah Dimakan • Kulit Dibuang ke Kompos',
    zero_waste_achieved: 'Bebas Sampah Makanan Tercapai',
    clean_plate_praise: 'Aksi ramah lingkungan yang luar biasa!',
    welcome_back: 'Selamat datang kembali,',
    tagline: 'Makan Bijak. Kurangi Sampah. Jaga Lingkungan.',
    current_streak: 'Runtun Berturut-turut',
    view_weekly_impact_tooltip: 'Klik untuk melihat rincian Dampak Mingguan',
    food_saved: 'Makanan Terselamatkan',
    eco_diversion_metric: 'Metrik pengalihan limbah',
    kg: 'kg',
    kg_this_week: 'kg minggu ini',
    view_weekly_impact_action: 'Dampak Mingguan',
    current_level: 'Level Saat Ini',
    xp_milestone_rank: 'Peringkat capaian XP',
    dashboard_sticker_shop_title: 'Toko Stiker Eko Kampus',
    dashboard_sticker_shop_desc: 'Koleksi berbagai stiker & lencana eko kampus dengan XP piring bersihmu!',
    of_campus_goal: 'Teralihkan',
    start_new_meal: 'Mulai Catat Makan',
    daily_tips: 'Tips Eko Harian',
    recent_meals: 'Riwayat Makanan Terbaru',
    restart: 'Mulai Ulang',
    unlocked: 'Terbuka',
    profile_stickers_title: 'Stiker Eko Kampus',
    profile_stickers_desc: 'Dibeli dengan XP piring bersih & bebas sampah makanan',
    profile_btn_visit_shop: 'Toko Stiker',
    profile_no_stickers_title: 'Belum Ada Stiker di Koleksimu',
    profile_no_stickers_desc: 'Tukarkan XP piring bersihmu dengan stiker keren BBS di Toko Stiker!',
    profile_btn_browse_stickers: 'Jelajahi Toko Stiker',
    weekly_impact: 'Dampak Mingguan',
    weekly_impact_desc: 'Pelacakan pengalihan makanan & piring bersih berdasarkan hari',
    total_saved: 'Total Terselamatkan',
    settings_language_desc: 'Pilih bahasa antarmuka aplikasi',
    customize: 'Sesuaikan',
    settings_data_history: 'Data & Riwayat Makan',
    restart_recent_meals: 'Mulai Ulang Riwayat Makan',
    restart_recent_meals_desc: 'Hapus pindaian makanan sebelumnya dan mulai baru dari 0 makanan',
    shop_cat_all: 'Semua Stiker',
    shop_cat_clean_plate: '🍽️ Piring Bersih',
    shop_cat_campus_pride: '🏫 Kampus BBS',
    shop_cat_zero_waste: '♻️ Bebas Sampah',
    shop_cat_nature_planet: '🌍 Bumi & Lautan',
    shop_cat_culinary: '🥗 Kuliner Hijau',
    sticker_rarity_common: 'Biasa',
    sticker_rarity_rare: 'Langka',
    sticker_rarity_epic: 'Epik',
    sticker_rarity_legendary: 'Legendaris',
    shop_badge_tag: 'Hadiah Eko Kampus BBS PIK',
    shop_title: 'Toko Stiker Eko Kampus',
    shop_subtitle: 'Tukarkan XP yang kamu raih dengan menghabiskan makanan dan mengembalikan piring bersih untuk stiker resmi eko kampus. Kumpulkan dari 1.000.000 edisi unik di 5 kategori!',
    shop_earn_tip: 'Habiskan piringmu untuk dapat +25 hingga +50 XP per makan!',
    shop_spendable_balance: 'Saldo XP Siap Pakai',
    shop_safe_rank: 'Peringkat Seumur Hidup Aman',
    shop_stickers_owned: 'Terkoleksi',
    shop_btn_scan_for_xp: 'Pindai Makanan untuk Raih Lebih Banyak XP',
    shop_tab_store: 'Toko Stiker',
    shop_tab_album: 'Album Stiker Saya',
    shop_search_placeholder: 'Cari stiker, #ID, atau kata kunci (misal: #777777, Harimau, Naga)...',
    shop_rarity_filter: 'Kelangkaan:',
    shop_showing_count: 'Menampilkan',
    shop_collected_label: 'stiker yang dikoleksi',
    shop_stickers_label: 'stiker',
    shop_album_empty_title: 'Belum ada stiker di albummu!',
    shop_no_stickers_found: 'Tidak ada stiker yang cocok dengan filtermu',
    shop_album_empty_desc: 'Kunjungi Toko Stiker untuk membeli stiker eko pertamamu dengan XP makanmu!',
    shop_try_other_filter: 'Coba bersihkan pencarian atau pilih kategori lain.',
    shop_btn_browse_store: 'Jelajahi Toko Stiker',
    shop_equipped_badge: 'Terpasang',
    shop_click_to_inspect: 'Periksa & Unduh',
    shop_btn_unequip: 'Lepas',
    shop_btn_equip_showcase: 'Pasang di Profil',
    shop_download_hint: 'Unduh Stiker PNG',
    shop_btn_buy: 'Beli Stiker',
    shop_need_more_prefix: 'Kurang',
    theme_modal_title: 'Tema Aplikasi & Tampilan',
    theme_modal_subtitle: 'Sesuaikan gaya visual kampus dan mode tampilan',
    display_mode_heading: 'Mode Tampilan',
    dark_mode_title: 'Mode Gelap',
    dark_mode_desc: 'Kontras dalam, hemat baterai',
    light_mode_title: 'Mode Terang',
    light_mode_desc: 'Tata letak siang hari yang cerah',
    color_palette_heading: 'Palet Warna & Identitas',
    btn_done_apply: 'Selesai & Terapkan Tampilan',
    question_food_category_desc: 'Pilih kategori makananmu untuk mengkalibrasi akurasi pengenalan AI dan metrik nutrisi.',
    question_food_item_desc: 'Pilih hidangan populer atau cari di bawah',
    search_dish_placeholder: 'Cari makanan populer atau ketik hidangan...',
    portion_size_heading: 'Ukuran Porsi',
    btn_proceed_camera: 'Lanjut ke Pemindaian Makanan',
    btn_verify_clean_plate: 'Verifikasi Piring Bersih & Klaim XP',
    toast_meals_restarted: '✨ Riwayat makan terbaru telah diatur ulang ke 0!',
    toast_signed_out_bbs: 'Keluar dari BBS PIK EcoEat',
    toast_challenge_joined: '🎉 Berhasil bergabung dengan tantangan keberlanjutan kampus!',
    planned_portion_size: 'Ukuran Porsi Direncanakan',
    selected_dining_profile: 'Profil Makanan Terpilih',
    portion: 'Porsi',
    options_available: 'Pilihan Tersedia',
    clear: 'Hapus',
    search: 'Cari',
    snapshot_captured: 'Foto Berhasil Diambil',
    starting_camera: 'Memulai Jendela Bidik Kamera AI...',
    camera_ready: 'Kamera Siap untuk Pemindaian',
    connecting_camera: 'Menghubungkan ke umpan kamera Anda...',
    point_at_food: 'Arahkan ke makananmu dan ketuk tombol bulat, atau ambil foto secara langsung.',
    take_photo_directly: 'Ambil Foto Langsung',
    retry_live: 'Coba Lagi Langsung',
    starting_camera_dots: 'Memulai Kamera...',
    active_snapshot: 'Foto Aktif',
    align_clean_plate: 'Sejajarkan Piring Bersih',
    center_food_frame: 'Pusatkan Makanan di Bingkai',
  },

  Spanish: {
    // General / Common
    app_name: 'EcoEat',
    school_name: 'BBS PIK',
    save: 'Guardar',
    cancel: 'Cancelar',
    done: 'Listo',
    close: 'Cerrar',
    customizable: 'Personalizable',
    verified: 'Verificado',
    back: 'Atrás',
    edit: 'Editar',
    level: 'Nivel',
    xp: 'XP',
    rank: 'Rango',
    streak: 'Racha',
    days: 'Días',
    days_left: 'días restantes',
    students: 'Estudiantes',
    rewards: 'Premios',
    view_details: 'Ver Detalles',
    view_all: 'Ver Todo',
    awesome: 'Genial',
    active: 'Activo',
    change: 'Cambiar',

    // Navigation
    nav_dashboard: 'Inicio',
    nav_capture: 'Escanear Comida',
    nav_leaderboard: 'Clasificación',
    nav_shop: 'Tienda de Stickers',
    nav_profile: 'Perfil',
    nav_settings: 'Ajustes',
    nav_menu: 'Menú',
    drawer_menu: 'Menú del Campus',
    drawer_themes: 'Tema y Apariencia',
    drawer_student_hub: 'Centro de Estudiantes BBS PIK',

    // Dashboard
    greeting_morning: 'Buenos días',
    greeting_afternoon: 'Buenas tardes',
    greeting_evening: 'Buenas noches',
    greeting_subtitle: '¿Listo para convertir tu almuerzo en impacto ecológico hoy?',
    stat_food_saved: 'Comida Salvada',
    stat_saved_this_week: 'Salvado esta semana',
    stat_level_title: 'Nivel de Guerrero Eco',
    stat_xp_to_next: 'XP para Nivel',
    stat_streak: 'Días de Racha',
    portion_title: 'Selecciona la Porción de Hoy',
    portion_small: 'Pequeña',
    portion_small_desc: 'Bocadillo ligero',
    portion_regular: 'Normal',
    portion_regular_desc: 'Apetito estándar',
    portion_large: 'Grande',
    portion_large_desc: 'Comida abundante',
    btn_scan_meal: 'Escanear y Registrar',
    btn_scan_meal_desc: 'Reconocimiento de porción por IA y plato limpio',
    section_campus_challenge: 'Desafío de Sostenibilidad del Campus',
    challenge_title: 'Meta de 1 Tonelada de Alimentos',
    challenge_diverted_so_far: 'kg desviados hasta ahora',
    section_recent_meals: 'Registro de Comidas Recientes',
    meal_clean_plate: 'Plato Limpio',
    meal_co2_diverted: 'CO2 Evitado',
    section_daily_tips: 'Consejos Ecológicos Diarios',
    section_campus_special: 'Especial del Comedor de Hoy',
    special_title: 'Ensalada Fresca Orgánica',
    special_desc: 'Lechuga crujiente local, tomates cherry, pepinos, garbanzos tostados y vinagreta de tahini y limón.',
    special_plant_rich: '100% Vegetal',
    special_station: 'Estación: Comedor Norte 2',

    // Capture & Camera Viewfinder
    capture_title: 'Escáner de Comida con IA',
    capture_step_1: '1. Selección de Comida y Porción',
    capture_step_2: '2. Escaneo de Comida con IA',
    capture_step_3: '3. Verificación de Plato Limpio',
    capture_step_choose_food: '1. Categoría y Plato',
    capture_step_scan_meal: '2. Escaneo de Comida con IA',
    capture_step_clean_plate: '3. Verificación de Plato Limpio',
    question_food_category: '¿Qué categoría de comida vas a comer?',
    question_food_item: '¿Qué plato vas a comer de esa categoría?',
    popular_options: 'Platos Populares del Comedor',
    custom_dish_placeholder: 'O escribe un plato personalizado...',
    continue_to_scan: 'Continuar al Escaneo del Plato',
    change_food: 'Cambiar Comida',
    dining_on: 'Comiendo',
    capture_align_meal: 'Encuadra la comida para reconocerla y estimar la porción',
    capture_align_plate: 'Encuadra el plato vacío para verificar plato limpio y ganar XP adicional',
    capture_btn_snap: 'Tomar Foto',
    capture_btn_retake: 'Repetir Foto',
    capture_analyzing: 'Analizando con IA...',
    capture_dish_name: 'Plato Reconocido',
    capture_calories: 'Calorías Estimadas',
    capture_portion_weight: 'Peso Estimado',
    capture_ingredients: 'Ingredientes Identificados',
    capture_carbon_diverted: 'Emisiones de CO2 Evitadas',
    capture_clean_plate_conf: 'Confianza de Plato Limpio',
    capture_waste_grams: 'Desperdicio Restante',
    capture_xp_reward: 'XP Ganados',
    capture_btn_proceed: '¡Todo Bien, Buen Provecho!',
    capture_btn_finish: 'Verificar Plato Limpio y Finalizar',
    capture_bonus_awarded: '¡+20 XP Bonus de Plato Limpio Desbloqueado!',
    capture_cancel: 'Cancelar Escaneo',

    // Leaderboard
    lb_title: 'Clasificación del Campus',
    lb_tab_bbs: 'BBS PIK',
    lb_tab_goal: 'Meta del Campus',
    lb_tab_class: 'Por Grado',
    lb_top_champion: 'Guerrero Eco #1 Actual',
    lb_student_rankings: 'Ranking de Estudiantes',
    lb_challenge_title: 'Desvío de 1 Tonelada de Comida',
    lb_challenge_sub: 'Desafío de Sostenibilidad BBS PIK',
    lb_your_rank: 'Tu Rango en el Campus',
    lb_class_rankings: 'Comida Salvada por Grado',

    // Profile
    profile_title: 'Perfil de Estudiante Eco',
    profile_edit_picture_hint: 'Haz clic para cambiar foto',
    profile_edit_btn: 'Editar Perfil',
    profile_summary: 'Resumen de Sostenibilidad',
    profile_total_food_saved: 'Total de Comida Salvada',
    profile_streak_days: 'Racha Diaria',
    profile_badges_unlocked: 'Insignias Ganadas',
    profile_current_tier: 'Nivel Actual',
    profile_badges_heading: 'Insignias Ecológicas',
    profile_view_all_badges: 'Ver Todas las Insignias',
    profile_meal_history: 'Historial de Comidas',

    // Settings
    settings_title: 'Ajustes',
    settings_account: 'Cuenta',
    settings_edit_profile: 'Editar Perfil y Foto',
    settings_change_password: 'Cambiar Contraseña',
    settings_school_id: 'ID Escolar',
    settings_preferences: 'Preferencias',
    settings_meal_reminders: 'Recordatorios de Comida',
    settings_challenge_updates: 'Actualizaciones de Desafíos',
    settings_language: 'Idioma',
    settings_greeting_color: 'Nombre y Color de Saludo',
    settings_theme: 'Tema y Apariencia',
    settings_dark_mode: 'Modo Oscuro',
    settings_dark_desc: 'Tema oscuro de alto contraste',
    settings_light_desc: 'Tema claro brillante',
    settings_sustainability: 'Sostenibilidad',
    settings_daily_goal: 'Meta Diaria de Alimentos Salvados',
    settings_campus_visibility: 'Visibilidad en el Campus',
    settings_campus_visibility_desc: 'Participar en los Desafíos de Campus BBS',
    settings_support: 'Soporte',
    settings_faq: 'Preguntas Frecuentes',
    settings_contact_us: 'Contacto',
    settings_privacy: 'Política de Privacidad',
    settings_sign_out: 'Cerrar Sesión',
    settings_sign_out_confirm: '¿Estás seguro de que deseas cerrar sesión en BBS PIK EcoEat?',

    // Modals
    modal_edit_profile: 'Editar Perfil de Estudiante',
    modal_choose_avatar: 'Elegir Avatar',
    modal_profile_pic: 'Foto de Perfil',
    modal_custom_photo_active: 'Foto Personalizada Activa',
    modal_upload_photo: 'Subir Foto',
    modal_take_photo: 'Tomar Foto',
    modal_link: 'Enlace',
    modal_photo_instructions: 'Sube cualquier imagen personal (PNG, JPG, WebP) desde tu dispositivo o cámara.',
    modal_drag_drop: 'Arrastra y suelta tu foto aquí, o busca un archivo',
    modal_supports_formats: 'Soporta formatos de imagen de hasta 8MB',
    modal_apply_url: 'Aplicar URL',
    modal_hide_presets: '▼ Ocultar Avatares Predefinidos',
    modal_show_presets: '▶ O elige un avatar de muestra',
    modal_full_name: 'Nombre Completo',
    modal_greeting_name: 'Nombre de Saludo (Inicio)',
    modal_grade: 'Grado',
    modal_save_changes: 'Guardar Cambios',
    modal_pw_title: 'Cambiar Contraseña',
    modal_current_pw: 'Contraseña Actual',
    modal_new_pw: 'Nueva Contraseña',
    modal_update_pw: 'Actualizar Contraseña',
    modal_pw_updated_title: '¡Contraseña Actualizada!',
    modal_pw_updated_desc: 'Tus credenciales de estudiante han sido actualizadas de forma segura.',
    modal_greeting_accent_title: 'Color del Saludo',
    modal_greeting_accent_desc: 'Personaliza el color del texto de bienvenida en tu panel EcoEat.',
    modal_theme_title: 'Apariencia y Temas',
    modal_theme_desc: 'Personaliza la paleta de colores y el ambiente visual de la aplicación.',
    modal_badge_gallery_title: 'Galería de Insignias del Campus',
    modal_special_title: 'Especial del Comedor',
    modal_close_special: 'Cerrar Especial',
    modal_reward_milestone: 'Hito de Recompensa',
    modal_rewards_list: 'Recompensas de la Comunidad Escolar:',

    // Toasts
    toast_profile_updated: 'Perfil actualizado con éxito',
    toast_preferences_saved: 'Preferencias guardadas',
    toast_language_changed: 'Idioma cambiado a',
    toast_greeting_updated: '¡Color de saludo actualizado!',
    toast_signed_out: 'Sesión cerrada exitosamente',
    toast_clean_verified: '✨ ¡Plato limpio verificado! ¡XP sumado a tu ranking del campus!',
    toast_level_up: '🎉 ¡Subiste de nivel! Has alcanzado el Nivel',

    // Authentication & Log-in Page
    auth_header_subtitle: 'Centro de Sostenibilidad y Nutrición del Campus',
    auth_select_language: 'Seleccionar Idioma',
    auth_pitch_badge: 'Centro Oficial de Comedor y Cero Residuos',
    auth_pitch_title_1: 'Convierte Cada Comida en',
    auth_pitch_title_2: 'Impacto Ecológico en el Campus',
    auth_pitch_desc: 'Escanea tu plato, minimiza el desperdicio de comida, gana XP para tu grado y ayuda a BBS PIK a alcanzar su meta semestral de 1.000 kg sin desperdicio.',
    auth_active_students: 'Estudiantes Activos',
    auth_food_diverted: 'Comida Salvada',
    auth_feature_sso: 'Inicio de Sesión Único con ID y Correo de Estudiante BBS PIK',
    auth_feature_ai: 'Cámara con visión IA para seguimiento automático de porciones y plato limpio',
    auth_feature_rankings: 'Clasificación en Tiempo Real entre Grados y Créditos de Comedor',
    auth_tab_signin: 'Iniciar Sesión Estudiante',
    auth_tab_signup: 'Crear Cuenta',
    auth_verification_title: 'Verificación de Cuenta:',
    auth_verification_desc: '1 cuenta oficial por estudiante de BBS PIK. Se prohíbe la duplicación de cuentas o registros repetidos.',
    auth_label_email_or_id: 'Correo o ID de Estudiante BBS PIK',
    auth_placeholder_email_or_id: 'ej. student.name@bbs-pik.edu',
    auth_label_password: 'Contraseña',
    auth_forgot_password: '¿Olvidaste?',
    auth_remember_me: 'Recordar mi inicio de sesión',
    auth_btn_signin: 'Ingresar al Centro del Campus',
    auth_new_to_ecoeat: '¿Nuevo en BBS PIK EcoEat?',
    auth_link_create_account: 'Crear Cuenta de Estudiante',
    auth_label_fullname: 'Nombre Completo del Estudiante',
    auth_placeholder_fullname: 'ej. Maya Lin',
    auth_label_grade: 'Grado',
    auth_label_section: 'Sección / Aula',
    auth_section_a: 'Sección A',
    auth_section_b: 'Sección B',
    auth_section_c: 'Sección C',
    auth_section_d: 'Sección D',
    auth_label_school_email: 'Correo Escolar',
    auth_placeholder_school_email: 'student@bbs-pik.edu',
    auth_label_create_password: 'Crear Contraseña',
    auth_placeholder_password_len: 'Al menos 6 caracteres',
    auth_btn_signup: 'Unirse al Programa Eco del Campus (+50 XP)',
    auth_terms_agreement: 'Al registrarte, aceptas la',
    auth_sustainability_charter: 'Carta de Sostenibilidad',
    auth_and: 'y la',
    auth_terms_of_service: 'Términos de Servicio',
    auth_already_have_account: '¿Ya tienes una cuenta?',
    auth_link_signin: 'Iniciar Sesión',
    auth_reset_pw_title: 'Restablecer Contraseña de Estudiante',
    auth_reset_pw_desc: 'Ingresa tu correo electrónico registrado de estudiante de BBS PIK. Te enviaremos un código seguro de restablecimiento a tu bandeja de entrada escolar.',
    auth_btn_send_reset: 'Enviar Enlace de Restablecimiento',
    auth_reset_sent_title: '¡Enlace de Restablecimiento Enviado!',
    auth_reset_sent_desc_prefix: 'Enviamos instrucciones a',
    auth_reset_sent_desc_suffix: '. Sigue el enlace del campus para elegir una nueva contraseña.',
    auth_btn_return_signin: 'Volver a Iniciar Sesión',
    auth_hide_password: 'Ocultar contraseña',
    auth_show_password: 'Ver contraseña',
    auth_footer_bbs: 'Bina Bangsa School',
    auth_footer_pik: 'Campus PIK',
    auth_footer_tagline: 'BBS PIK EcoEat • Programa de Sostenibilidad y Reducción de Desperdicios del Campus 2026',
    auth_err_email_id_required: 'Por favor, introduce tu correo o ID de estudiante de BBS PIK',
    auth_err_password_required: 'Por favor, introduce la contraseña de tu cuenta',
    auth_err_failed: 'Error de autenticación. Por favor, verifica tus credenciales.',
    auth_err_name_required: 'Por favor, proporciona el nombre completo del estudiante',
    auth_err_email_required: 'Por favor, proporciona un correo de estudiante de BBS PIK válido',
    auth_err_email_invalid: 'Por favor, proporciona un correo BBS PIK válido (ej. name@bbs-pik.edu)',
    auth_err_password_short: 'La contraseña debe tener al menos 6 caracteres',
    auth_success_signup: '¡Cuenta de estudiante creada con éxito! Iniciando sesión...',
    auth_err_registration_failed: 'Error al registrar la cuenta. Se prohíbe duplicar cuentas de estudiantes existentes.',

    // Comprehensive UI Keys
    step: 'Paso',
    of: 'de',
    clean_plate_bonus_hint: 'La visión inteligente verifica los alimentos, los macros y la reducción de CO2.',
    finished_fruit_verified: 'Fruta terminada 100% verificada',
    clean_plate_verified: 'Plato limpio 100% verificado',
    finished_fruit_title: 'Toda la fruta comida • Cáscaras compostadas',
    zero_waste_achieved: 'Cero desperdicio alcanzado',
    clean_plate_praise: '¡Excelente acción ecológica!',
    welcome_back: '¡Bienvenido de nuevo,',
    tagline: 'Come inteligente. Ahorra más. Sé verde.',
    current_streak: 'Racha actual',
    view_weekly_impact_tooltip: 'Haz clic para ver el desglose del impacto semanal',
    food_saved: 'Comida salvada',
    eco_diversion_metric: 'Métrica de desvío ecológico',
    kg: 'kg',
    kg_this_week: 'kg esta semana',
    view_weekly_impact_action: 'Impacto semanal',
    current_level: 'Nivel actual',
    xp_milestone_rank: 'Rango por hitos de XP',
    dashboard_sticker_shop_title: 'Tienda de stickers ecológicos del campus',
    dashboard_sticker_shop_desc: '¡Colecciona stickers y medallas ecológicas con los puntos XP de tus platos limpios!',
    of_campus_goal: 'Desviado',
    start_new_meal: 'Registrar nueva comida',
    daily_tips: 'Consejos ecológicos diarios',
    recent_meals: 'Comidas recientes',
    restart: 'Reiniciar',
    unlocked: 'Desbloqueado',
    profile_stickers_title: 'Stickers ecológicos del campus',
    profile_stickers_desc: 'Comprado con XP de platos limpios y cero desperdicio',
    profile_btn_visit_shop: 'Tienda de stickers',
    profile_no_stickers_title: '¡Aún no tienes stickers en tu colección!',
    profile_no_stickers_desc: '¡Canjea tus puntos XP de comedor por geniales stickers de BBS en la tienda!',
    profile_btn_browse_stickers: 'Explorar tienda de stickers',
    weekly_impact: 'Impacto semanal',
    weekly_impact_desc: 'Seguimiento de platos limpios y desvío de comida por día de la semana',
    total_saved: 'Total salvado',
    settings_language_desc: 'Elige el idioma de la interfaz',
    customize: 'Personalizar',
    settings_data_history: 'Datos y comidas',
    restart_recent_meals: 'Reiniciar registro de comidas recientes',
    restart_recent_meals_desc: 'Borra los escaneos anteriores y empieza desde 0 comidas',
    shop_cat_all: 'Todos los stickers',
    shop_cat_clean_plate: '🍽️ Plato Limpio',
    shop_cat_campus_pride: '🏫 Campus BBS',
    shop_cat_zero_waste: '♻️ Cero Residuos',
    shop_cat_nature_planet: '🌍 Planeta y Océano',
    shop_cat_culinary: '🥗 Culinario',
    sticker_rarity_common: 'Común',
    sticker_rarity_rare: 'Raro',
    sticker_rarity_epic: 'Épico',
    sticker_rarity_legendary: 'Legendario',
    shop_badge_tag: 'Premios ecológicos del campus BBS PIK',
    shop_title: 'Tienda de stickers ecológicos',
    shop_subtitle: '¡Canjea los puntos XP que ganaste al terminar tu comida por stickers oficiales del campus! ¡Colecciona ediciones únicas en 5 categorías!',
    shop_earn_tip: '¡Deja tu plato limpio para ganar de +25 a +50 XP por comida!',
    shop_spendable_balance: 'Saldo de XP canjeable',
    shop_safe_rank: 'Rango vitalicio protegido',
    shop_stickers_owned: 'Coleccionados',
    shop_btn_scan_for_xp: 'Escanear comida para ganar más XP',
    shop_tab_store: 'Tienda de stickers',
    shop_tab_album: 'Mi álbum de stickers',
    shop_search_placeholder: 'Buscar stickers, #ID o palabra clave (ej. #777777, Tigre, Dragón)...',
    shop_rarity_filter: 'Rareza:',
    shop_showing_count: 'Mostrando',
    shop_collected_label: 'stickers coleccionados',
    shop_stickers_label: 'stickers',
    shop_album_empty_title: '¡Aún no hay stickers en tu álbum!',
    shop_no_stickers_found: 'Ningún sticker coincide con tu filtro',
    shop_album_empty_desc: '¡Explora la tienda de stickers para comprar tu primer sticker con tus puntos XP!',
    shop_try_other_filter: 'Intenta borrar la búsqueda o seleccionar otra categoría.',
    shop_btn_browse_store: 'Explorar tienda de stickers',
    shop_equipped_badge: 'Equipado',
    shop_click_to_inspect: 'Inspeccionar y descargar',
    shop_btn_unequip: 'Desequipar',
    shop_btn_equip_showcase: 'Equipar en perfil',
    shop_download_hint: 'Descargar sticker PNG',
    shop_btn_buy: 'Comprar sticker',
    shop_need_more_prefix: 'Necesitas',
    theme_modal_title: 'Temas y apariencia de la aplicación',
    theme_modal_subtitle: 'Personaliza los estilos visuales del campus y el modo de pantalla',
    display_mode_heading: 'Modo de visualización',
    dark_mode_title: 'Modo oscuro',
    dark_mode_desc: 'Alto contraste, ahorro de batería',
    light_mode_title: 'Modo claro',
    light_mode_desc: 'Diseño diurno nítido',
    color_palette_heading: 'Paleta de colores e identidad',
    btn_done_apply: 'Listo y aplicar apariencia',
    question_food_category_desc: 'Selecciona tu categoría de comida para calibrar la precisión del reconocimiento por IA.',
    question_food_item_desc: 'Selecciona un plato popular o busca abajo',
    search_dish_placeholder: 'Buscar comidas populares o escribir plato personalizado...',
    portion_size_heading: 'Tamaño de la porción',
    btn_proceed_camera: 'Continuar al escaneo de comida',
    btn_verify_clean_plate: 'Verificar plato limpio y reclamar XP',
    toast_meals_restarted: '¡✨ El registro de comidas recientes se ha reiniciado a 0!',
    toast_signed_out_bbs: 'Sesión cerrada de BBS PIK EcoEat',
    toast_challenge_joined: '¡🎉 Te has unido al desafío de sostenibilidad del campus!',
    planned_portion_size: 'Tamaño de porción planificado',
    selected_dining_profile: 'Perfil de comida seleccionado',
    portion: 'Porción',
    options_available: 'Opciones disponibles',
    clear: 'Borrar',
    search: 'Buscar',
    snapshot_captured: 'Captura tomada',
    starting_camera: 'Iniciando visor de cámara con IA...',
    camera_ready: 'Cámara lista para escanear',
    connecting_camera: 'Conectando con la cámara...',
    point_at_food: 'Apunta a tu comida y presiona el botón redondo, o toma una foto directamente.',
    take_photo_directly: 'Tomar foto directamente',
    retry_live: 'Reintentar en vivo',
    starting_camera_dots: 'Iniciando cámara...',
    active_snapshot: 'Captura activa',
    align_clean_plate: 'Alinear plato limpio',
    center_food_frame: 'Centra la comida en el encuadre',
  },

  French: {
    // General / Common
    app_name: 'EcoEat',
    school_name: 'BBS PIK',
    save: 'Enregistrer',
    cancel: 'Annuler',
    done: 'Terminé',
    close: 'Fermer',
    customizable: 'Personnalisable',
    verified: 'Vérifié',
    back: 'Retour',
    edit: 'Modifier',
    level: 'Niveau',
    xp: 'XP',
    rank: 'Rang',
    streak: 'Série',
    days: 'Jours',
    days_left: 'jours restants',
    students: 'Étudiants',
    rewards: 'Récompenses',
    view_details: 'Voir les Détails',
    view_all: 'Voir Tout',
    awesome: 'Super',
    active: 'Actif',
    change: 'Changer',

    // Navigation
    nav_dashboard: 'Accueil',
    nav_capture: 'Scanner Repas',
    nav_leaderboard: 'Classement',
    nav_shop: 'Boutique Stickers',
    nav_profile: 'Profil',
    nav_settings: 'Paramètres',
    nav_menu: 'Menu',
    drawer_menu: 'Menu Campus',
    drawer_themes: 'Thème & Apparence',
    drawer_student_hub: 'Pôle Étudiant BBS PIK',

    // Dashboard
    greeting_morning: 'Bonjour',
    greeting_afternoon: 'Bon après-midi',
    greeting_evening: 'Bonsoir',
    greeting_subtitle: 'Prêt à transformer votre déjeuner en impact écologique aujourd’hui ?',
    stat_food_saved: 'Nourriture Sauvée',
    stat_saved_this_week: 'Sauvé cette semaine',
    stat_level_title: 'Niveau Éco Guerrier',
    stat_xp_to_next: 'XP pour Niveau',
    stat_streak: 'Jours Consécutifs',
    portion_title: "Sélectionnez la Portion d'Aujourd'hui",
    portion_small: 'Petite',
    portion_small_desc: 'Collation légère',
    portion_regular: 'Normale',
    portion_regular_desc: 'Faim standard',
    portion_large: 'Grande',
    portion_large_desc: 'Repas copieux',
    btn_scan_meal: 'Scanner et Enregistrer',
    btn_scan_meal_desc: 'Reconnaissance de portion IA & assiette propre',
    section_campus_challenge: 'Défi Durabilité du Campus',
    challenge_title: 'Objectif 1 Tonne de Nourriture Sauvée',
    challenge_diverted_so_far: 'kg sauvés à ce jour',
    section_recent_meals: 'Historique des Repas Récents',
    meal_clean_plate: 'Assiette Propre',
    meal_co2_diverted: 'CO2 Évité',
    section_daily_tips: 'Conseils Éco du Jour',
    section_campus_special: 'Spécial Réfectoire du Jour',
    special_title: 'Salade Fraîche du Jardin Bio',
    special_desc: 'Laitue croquante locale, tomates cerises, concombres, pois chiches rôtis et vinaigrette maison tahini-citron.',
    special_plant_rich: '100% Végétal',
    special_station: 'Lieu : Réfectoire Nord 2',

    // Capture & Camera Viewfinder
    capture_title: 'Scanner de Repas IA',
    capture_step_1: '1. Choix du Plat & Portion',
    capture_step_2: '2. Scan de Repas IA',
    capture_step_3: '3. Vérification Assiette Propre',
    capture_step_choose_food: '1. Catégorie & Plat',
    capture_step_scan_meal: '2. Scan de Repas IA',
    capture_step_clean_plate: '3. Vérification Assiette Propre',
    question_food_category: 'Quelle catégorie de cuisine allez-vous manger ?',
    question_food_item: 'Quel plat allez-vous manger dans cette catégorie ?',
    popular_options: 'Plats Populaires du Restaurant',
    custom_dish_placeholder: 'Ou écrivez un plat personnalisé...',
    continue_to_scan: "Continuer vers le Scan de l'Assiette",
    change_food: 'Changer de Plat',
    dining_on: 'Au menu',
    capture_align_meal: 'Cadrez le repas pour identifier les ingrédients et estimer la portion',
    capture_align_plate: "Cadrez l'assiette vide pour vérifier la propreté et gagner des bonus XP",
    capture_btn_snap: 'Prendre la Photo',
    capture_btn_retake: 'Reprendre la Photo',
    capture_analyzing: 'Analyse IA en cours...',
    capture_dish_name: 'Plat Reconnu',
    capture_calories: 'Calories Estimées',
    capture_portion_weight: 'Poids Estimé',
    capture_ingredients: 'Ingrédients Identifiés',
    capture_carbon_diverted: 'Émissions CO2 Évitées',
    capture_clean_plate_conf: 'Score Assiette Propre',
    capture_waste_grams: 'Déchets Restants',
    capture_xp_reward: 'XP Gagnés',
    capture_btn_proceed: 'Parfait, Bon Appétit !',
    capture_btn_finish: 'Valider Assiette Propre & Terminer',
    capture_bonus_awarded: '+20 XP Bonus Assiette Propre Débloqué !',
    capture_cancel: "Annuler l'Analyse",

    // Leaderboard
    lb_title: 'Classement du Campus',
    lb_tab_bbs: 'BBS PIK',
    lb_tab_goal: 'Objectif Campus',
    lb_tab_class: 'Par Classe',
    lb_top_champion: 'Guerrier Éco #1 Actuel',
    lb_student_rankings: 'Classement des Élèves',
    lb_challenge_title: '1 Tonne de Nourriture Sauvée',
    lb_challenge_sub: 'Défi Durabilité BBS PIK',
    lb_your_rank: 'Votre Rang sur le Campus',
    lb_class_rankings: 'Nourriture Sauvée par Niveau',

    // Profile
    profile_title: 'Profil Éco Élève',
    profile_edit_picture_hint: 'Cliquez pour changer la photo',
    profile_edit_btn: 'Modifier le Profil',
    profile_summary: 'Résumé de Durabilité',
    profile_total_food_saved: 'Total Nourriture Sauvée',
    profile_streak_days: 'Série Quotidienne',
    profile_badges_unlocked: 'Badges Obtenus',
    profile_current_tier: 'Rang Actuel',
    profile_badges_heading: 'Badges Écologiques',
    profile_view_all_badges: 'Voir Tous les Badges',
    profile_meal_history: 'Historique des Repas',

    // Settings
    settings_title: 'Paramètres',
    settings_account: 'Compte',
    settings_edit_profile: 'Modifier Profil & Photo',
    settings_change_password: 'Changer Mot de Passe',
    settings_school_id: 'Identifiant Scolaire',
    settings_preferences: 'Préférences',
    settings_meal_reminders: 'Rappels de Repas',
    settings_challenge_updates: 'Mises à Jour des Défis',
    settings_language: 'Langue',
    settings_greeting_color: 'Nom & Couleur de Salutation',
    settings_theme: 'Thème & Apparence',
    settings_dark_mode: 'Mode Sombre',
    settings_dark_desc: 'Thème sombre à fort contraste',
    settings_light_desc: 'Thème clair lumineux',
    settings_sustainability: 'Durabilité',
    settings_daily_goal: 'Objectif Quotidien Nourriture Sauvée',
    settings_campus_visibility: 'Visibilité Campus',
    settings_campus_visibility_desc: 'Participer aux Défis Campus BBS',
    settings_support: 'Assistance',
    settings_faq: 'Foire Aux Questions',
    settings_contact_us: 'Nous Contacter',
    settings_privacy: 'Politique de Confidentialité',
    settings_sign_out: 'Se Déconnecter',
    settings_sign_out_confirm: 'Êtes-vous sûr de vouloir vous déconnecter de BBS PIK EcoEat ?',

    // Modals
    modal_edit_profile: 'Modifier le Profil Élève',
    modal_choose_avatar: 'Choisir un Avatar',
    modal_profile_pic: 'Photo de Profil',
    modal_custom_photo_active: 'Photo Personnalisée Active',
    modal_upload_photo: 'Téléverser Photo',
    modal_take_photo: 'Prendre une Photo',
    modal_link: 'Lien',
    modal_photo_instructions: 'Téléversez une image personnelle (PNG, JPG, WebP) depuis votre appareil ou caméra.',
    modal_drag_drop: 'Glissez-déposez votre photo ici, ou parcourez les fichiers',
    modal_supports_formats: "Prend en charge tous les formats d'image jusqu'à 8 Mo",
    modal_apply_url: 'Appliquer URL',
    modal_hide_presets: '▼ Masquer les Avatars Exemples',
    modal_show_presets: '▶ Ou choisir un avatar exemple',
    modal_full_name: 'Nom Complet',
    modal_greeting_name: "Nom d'Accueil (Tableau de Bord)",
    modal_grade: 'Classe',
    modal_save_changes: 'Enregistrer les Modifications',
    modal_pw_title: 'Changer le Mot de Passe',
    modal_current_pw: 'Mot de Passe Actuel',
    modal_new_pw: 'Nouveau Mot de Passe',
    modal_update_pw: 'Mettre à Jour le Mot de Passe',
    modal_pw_updated_title: 'Mot de Passe Mis à Jour !',
    modal_pw_updated_desc: 'Vos identifiants scolaires ont été mis à jour en toute sécurité.',
    modal_greeting_accent_title: 'Couleur de Salutation',
    modal_greeting_accent_desc: 'Personnalisez la couleur du message de bienvenue sur votre tableau de bord.',
    modal_theme_title: 'Apparence & Thèmes',
    modal_theme_desc: "Personnalisez la palette de couleurs et l'ambiance visuelle.",
    modal_badge_gallery_title: 'Galerie des Badges du Campus',
    modal_special_title: 'Spécial Réfectoire du Campus',
    modal_close_special: 'Fermer le Spécial',
    modal_reward_milestone: 'Palier de Récompense',
    modal_rewards_list: "Récompenses de l'Établissement :",

    // Toasts
    toast_profile_updated: 'Profil mis à jour avec succès',
    toast_preferences_saved: 'Préférences enregistrées',
    toast_language_changed: 'Langue modifiée en',
    toast_greeting_updated: 'Couleur de salutation mise à jour !',
    toast_signed_out: 'Déconnexion réussie',
    toast_clean_verified: '✨ Assiette propre validée ! XP ajouté à votre classement !',
    toast_level_up: '🎉 Niveau supérieur ! Vous avez atteint le Niveau',

    // Authentication & Log-in Page
    auth_header_subtitle: 'Pôle Durabilité & Nutrition du Campus',
    auth_select_language: 'Sélectionner la Langue',
    auth_pitch_badge: 'Pôle Officiel Restauration Campus & Zéro Déchet',
    auth_pitch_title_1: 'Transformez Chaque Repas en',
    auth_pitch_title_2: 'Impact Écologique sur le Campus',
    auth_pitch_desc: 'Scannez votre assiette, réduisez le gaspillage alimentaire, gagnez des XP pour votre classe et aidez BBS PIK à atteindre son objectif semestriel de 1 000 kg zéro déchet.',
    auth_active_students: 'Élèves Actifs',
    auth_food_diverted: 'Nourriture Sauvée',
    auth_feature_sso: 'Connexion Unique avec Identifiant & E-mail Élève BBS PIK',
    auth_feature_ai: 'Caméra IA Vision pour le suivi automatique des portions et des assiettes propres',
    auth_feature_rankings: 'Classement en Temps Réel entre Niveaux & Crédits Restauration',
    auth_tab_signin: 'Connexion Élève',
    auth_tab_signup: 'Créer un Compte',
    auth_verification_title: 'Vérification du Compte :',
    auth_verification_desc: '1 compte officiel par élève BBS PIK. La copie de compte ou l’inscription en double est interdite.',
    auth_label_email_or_id: 'E-mail ou Identifiant Élève BBS PIK',
    auth_placeholder_email_or_id: 'ex. student.name@bbs-pik.edu',
    auth_label_password: 'Mot de Passe',
    auth_forgot_password: 'Oublié ?',
    auth_remember_me: 'Se souvenir de mon identifiant',
    auth_btn_signin: 'Se Connecter au Pôle Campus',
    auth_new_to_ecoeat: 'Nouveau sur BBS PIK EcoEat ?',
    auth_link_create_account: 'Créer un Compte Élève',
    auth_label_fullname: 'Nom Complet de l’Élève',
    auth_placeholder_fullname: 'ex. Maya Lin',
    auth_label_grade: 'Classe',
    auth_label_section: 'Section / Groupe',
    auth_section_a: 'Section A',
    auth_section_b: 'Section B',
    auth_section_c: 'Section C',
    auth_section_d: 'Section D',
    auth_label_school_email: 'E-mail Scolaire',
    auth_placeholder_school_email: 'student@bbs-pik.edu',
    auth_label_create_password: 'Créer un Mot de Passe',
    auth_placeholder_password_len: 'Au moins 6 caractères',
    auth_btn_signup: 'Rejoindre le Programme Éco Campus (+50 XP)',
    auth_terms_agreement: 'En vous inscrivant, vous acceptez la',
    auth_sustainability_charter: 'Charte de Durabilité',
    auth_and: 'et la',
    auth_terms_of_service: 'Conditions d’Utilisation',
    auth_already_have_account: 'Vous avez déjà un compte ?',
    auth_link_signin: 'Connexion',
    auth_reset_pw_title: 'Réinitialiser le Mot de Passe Élève',
    auth_reset_pw_desc: 'Entrez votre adresse e-mail d’élève BBS PIK enregistrée. Nous enverrons un code de réinitialisation sécurisé dans votre boîte de réception scolaire.',
    auth_btn_send_reset: 'Envoyer le Lien de Réinitialisation',
    auth_reset_sent_title: 'Lien de Réinitialisation Envoyé !',
    auth_reset_sent_desc_prefix: 'Nous avons envoyé des instructions à',
    auth_reset_sent_desc_suffix: '. Suivez le lien pour choisir un nouveau mot de passe.',
    auth_btn_return_signin: 'Retour à la Connexion',
    auth_hide_password: 'Masquer le mot de passe',
    auth_show_password: 'Voir le mot de passe',
    auth_footer_bbs: 'Bina Bangsa School',
    auth_footer_pik: 'Campus PIK',
    auth_footer_tagline: 'BBS PIK EcoEat • Programme de Durabilité et de Réduction du Gaspillage Alimentaire 2026',
    auth_err_email_id_required: 'Veuillez saisir votre e-mail ou identifiant élève BBS PIK',
    auth_err_password_required: 'Veuillez saisir le mot de passe de votre compte',
    auth_err_failed: 'Échec de l’authentification. Veuillez vérifier vos identifiants.',
    auth_err_name_required: 'Veuillez fournir le nom complet de l’élève',
    auth_err_email_required: 'Veuillez fournir un e-mail d’élève BBS PIK valide',
    auth_err_email_invalid: 'Veuillez fournir un e-mail BBS PIK valide (ex. name@bbs-pik.edu)',
    auth_err_password_short: 'Le mot de passe doit comporter au moins 6 caractères',
    auth_success_signup: 'Compte élève créé avec succès ! Connexion en cours...',
    auth_err_registration_failed: 'Échec de la création du compte. La copie de comptes d’élèves existants est interdite.',

    // Comprehensive UI Keys
    step: 'Étape',
    of: 'sur',
    clean_plate_bonus_hint: 'La vision intelligente vérifie les aliments, les macros et la réduction de CO2.',
    finished_fruit_verified: 'Fruits terminés 100% vérifiés',
    clean_plate_verified: 'Assiette propre 100% vérifiée',
    finished_fruit_title: 'Tous les fruits mangés • Épluchures compostées',
    zero_waste_achieved: 'Zéro déchet atteint',
    clean_plate_praise: 'Action écologique remarquable !',
    welcome_back: 'Bon retour,',
    tagline: 'Mangez malin. Gaspillez moins. Vivez vert.',
    current_streak: 'Série actuelle',
    view_weekly_impact_tooltip: 'Cliquez pour voir le bilan hebdomadaire',
    food_saved: 'Nourriture sauvée',
    eco_diversion_metric: 'Métrique d’éco-détournement',
    kg: 'kg',
    kg_this_week: 'kg cette semaine',
    view_weekly_impact_action: 'Impact hebdomadaire',
    current_level: 'Niveau actuel',
    xp_milestone_rank: 'Rang jalon XP',
    dashboard_sticker_shop_title: 'Boutique de stickers éco du campus',
    dashboard_sticker_shop_desc: 'Collectionnez des stickers et badges éco grâce à vos points XP assiette propre !',
    of_campus_goal: 'Détourné',
    start_new_meal: 'Enregistrer un repas',
    daily_tips: 'Astuces éco du jour',
    recent_meals: 'Repas récents',
    restart: 'Réinitialiser',
    unlocked: 'Débloqué',
    profile_stickers_title: 'Stickers éco du campus',
    profile_stickers_desc: 'Acheté avec les XP assiette propre et zéro déchet',
    profile_btn_visit_shop: 'Boutique de stickers',
    profile_no_stickers_title: 'Aucun sticker dans votre collection pour l’instant !',
    profile_no_stickers_desc: 'Échangez vos points XP contre de super stickers BBS dans la boutique !',
    profile_btn_browse_stickers: 'Explorer la boutique',
    weekly_impact: 'Impact hebdomadaire',
    weekly_impact_desc: 'Suivi du détournement alimentaire et des assiettes propres par jour',
    total_saved: 'Total sauvé',
    settings_language_desc: 'Choisir la langue de l’interface',
    customize: 'Personnaliser',
    settings_data_history: 'Données et repas',
    restart_recent_meals: 'Réinitialiser l’historique des repas récents',
    restart_recent_meals_desc: 'Effacez les scans précédents pour repartir de 0 repas',
    shop_cat_all: 'Tous les stickers',
    shop_cat_clean_plate: '🍽️ Assiette Propre',
    shop_cat_campus_pride: '🏫 Campus BBS',
    shop_cat_zero_waste: '♻️ Zéro Déchet',
    shop_cat_nature_planet: '🌍 Planète et Océan',
    shop_cat_culinary: '🥗 Culinaire',
    sticker_rarity_common: 'Courant',
    sticker_rarity_rare: 'Rare',
    sticker_rarity_epic: 'Épique',
    sticker_rarity_legendary: 'Légendaire',
    shop_badge_tag: 'Récompenses éco du campus BBS PIK',
    shop_title: 'Boutique de stickers éco',
    shop_subtitle: 'Échangez les points XP gagnés en finissant votre repas contre des stickers officiels du campus ! Collectionnez des éditions uniques réparties en 5 catégories !',
    shop_earn_tip: 'Finissez votre assiette pour gagner de +25 à +50 XP par repas !',
    shop_spendable_balance: 'Solde de points XP échangeables',
    shop_safe_rank: 'Rang permanent préservé',
    shop_stickers_owned: 'Collectionnés',
    shop_btn_scan_for_xp: 'Scanner un repas pour gagner plus de points XP',
    shop_tab_store: 'Boutique de stickers',
    shop_tab_album: 'Mon album de stickers',
    shop_search_placeholder: 'Rechercher des stickers, #ID ou mot-clé (ex. #777777, Tigre, Dragon)...',
    shop_rarity_filter: 'Rareté :',
    shop_showing_count: 'Affichage',
    shop_collected_label: 'stickers collectionnés',
    shop_stickers_label: 'stickers',
    shop_album_empty_title: 'Aucun sticker dans votre album pour l’instant !',
    shop_no_stickers_found: 'Aucun sticker ne correspond à vos filtres',
    shop_album_empty_desc: 'Parcourez la boutique pour acheter votre premier sticker éco avec vos points XP !',
    shop_try_other_filter: 'Essayez d’effacer votre recherche ou de sélectionner une autre catégorie.',
    shop_btn_browse_store: 'Explorer la boutique',
    shop_equipped_badge: 'Équipé',
    shop_click_to_inspect: 'Inspecter et télécharger',
    shop_btn_unequip: 'Retirer',
    shop_btn_equip_showcase: 'Équiper sur le profil',
    shop_download_hint: 'Télécharger le sticker PNG',
    shop_btn_buy: 'Acheter le sticker',
    shop_need_more_prefix: 'Besoin de',
    theme_modal_title: 'Thèmes et apparence de l’application',
    theme_modal_subtitle: 'Personnalisez les styles visuels du campus et le mode d’affichage',
    display_mode_heading: 'Mode d’affichage',
    dark_mode_title: 'Mode sombre',
    dark_mode_desc: 'Contraste élevé, économie de batterie',
    light_mode_title: 'Mode clair',
    light_mode_desc: 'Affichage clair et lumineux',
    color_palette_heading: 'Palette de couleurs et identité',
    btn_done_apply: 'Terminer et appliquer',
    question_food_category_desc: 'Sélectionnez votre catégorie d’aliments pour calibrer la précision de reconnaissance IA.',
    question_food_item_desc: 'Sélectionnez un plat populaire ou recherchez ci-dessous',
    search_dish_placeholder: 'Rechercher un plat populaire ou taper un plat...',
    portion_size_heading: 'Taille de la portion',
    btn_proceed_camera: 'Passer au scan du repas',
    btn_verify_clean_plate: 'Vérifier l’assiette propre et réclamer les XP',
    toast_meals_restarted: '✨ L’historique des repas récents a été réinitialisé à 0 !',
    toast_signed_out_bbs: 'Déconnexion de BBS PIK EcoEat',
    toast_challenge_joined: '🎉 Vous avez rejoint le défi de durabilité du campus !',
    planned_portion_size: 'Portion prévue',
    selected_dining_profile: 'Profil de repas sélectionné',
    portion: 'Portion',
    options_available: 'Options disponibles',
    clear: 'Effacer',
    search: 'Rechercher',
    snapshot_captured: 'Photo capturée',
    starting_camera: 'Démarrage du viseur caméra IA...',
    camera_ready: 'Caméra prête pour le scan',
    connecting_camera: 'Connexion au flux de votre caméra...',
    point_at_food: 'Pointez vos aliments et appuyez sur le bouton rond, ou prenez directement une photo.',
    take_photo_directly: 'Prendre une photo directement',
    retry_live: 'Réessayer en direct',
    starting_camera_dots: 'Démarrage de la caméra...',
    active_snapshot: 'Photo active',
    align_clean_plate: 'Aligner l’assiette propre',
    center_food_frame: 'Centrez la nourriture dans le cadre',
  },

  Mandarin: {
    // General / Common
    app_name: 'EcoEat',
    school_name: 'BBS PIK',
    save: '保存',
    cancel: '取消',
    done: '完成',
    close: '关闭',
    customizable: '可自定义',
    verified: '已认证',
    back: '返回',
    edit: '编辑',
    level: '等级',
    xp: '经验值',
    rank: '排名',
    streak: '连续天数',
    days: '天',
    days_left: '天剩余',
    students: '名学生',
    rewards: '奖励',
    view_details: '查看详情',
    view_all: '查看全部',
    awesome: '太棒了',
    active: '当前使用',
    change: '更换',

    // Navigation
    nav_dashboard: '首页',
    nav_capture: '扫描餐食',
    nav_leaderboard: '排行榜',
    nav_shop: '贴纸商店',
    nav_profile: '个人主页',
    nav_settings: '设置',
    nav_menu: '菜单',
    drawer_menu: '校园菜单',
    drawer_themes: '主题与外观',
    drawer_student_hub: 'BBS PIK 学生中心',

    // Dashboard
    greeting_morning: '早上好',
    greeting_afternoon: '下午好',
    greeting_evening: '晚上好',
    greeting_subtitle: '准备好今天通过午餐为校园环保贡献力量了吗？',
    stat_food_saved: '节约粮食',
    stat_saved_this_week: '本周节约',
    stat_level_title: '环保卫士等级',
    stat_xp_to_next: '距离下一级经验',
    stat_streak: '连续光盘天数',
    portion_title: '选择今日用餐分量',
    portion_small: '小份',
    portion_small_desc: '轻食 / 点心',
    portion_regular: '标准',
    portion_regular_desc: '普通食量',
    portion_large: '大份',
    portion_large_desc: '大食量餐食',
    btn_scan_meal: '扫描并记录餐食',
    btn_scan_meal_desc: 'AI 分量识别与光盘打卡',
    section_campus_challenge: '校园可持续挑战赛',
    challenge_title: '1 吨粮食减废目标',
    challenge_diverted_so_far: '公斤已减废',
    section_recent_meals: '最近用餐记录',
    meal_clean_plate: '光盘率',
    meal_co2_diverted: '减少碳排',
    section_daily_tips: '每日校园环保小贴士',
    section_campus_special: '今日餐厅特供',
    special_title: '有机鲜蔬农场沙拉',
    special_desc: '本地有机生菜、圣女果、黄瓜、烤鹰嘴豆与特调柠檬芝麻酱。',
    special_plant_rich: '100% 植物性营养',
    special_station: '取餐点：北二食堂',

    // Capture & Camera Viewfinder
    capture_title: 'AI 餐食扫描仪',
    capture_step_1: '1. 选择美食与分量',
    capture_step_2: '2. AI 餐食扫描',
    capture_step_3: '3. 光盘清洁验证',
    capture_step_choose_food: '1. 美食分类与菜品',
    capture_step_scan_meal: '2. AI 餐食扫描',
    capture_step_clean_plate: '3. 光盘清洁验证',
    question_food_category: '您今天要品尝哪类风味美食？',
    question_food_item: '您准备享用该分类中的哪道菜品？',
    popular_options: '校园食堂热门菜品',
    custom_dish_placeholder: '或输入自定义菜品名称...',
    continue_to_scan: '继续进行餐盘扫描',
    change_food: '更改菜品',
    dining_on: '今日享用',
    capture_align_meal: '将餐盘对准取景框以识别食材并估算分量',
    capture_align_plate: '将空盘对准取景框以进行光盘验证并领取经验奖励',
    capture_btn_snap: '拍照记录',
    capture_btn_retake: '重新拍摄',
    capture_analyzing: 'AI 智能分析中...',
    capture_dish_name: '识别菜品',
    capture_calories: '预估热量',
    capture_portion_weight: '预估分量',
    capture_ingredients: '识别食材',
    capture_carbon_diverted: '减少 CO2 排放',
    capture_clean_plate_conf: '光盘清洁度',
    capture_waste_grams: '剩余厨余',
    capture_xp_reward: '获得经验值',
    capture_btn_proceed: '确认无误，开始用餐！',
    capture_btn_finish: '验证光盘并完成',
    capture_bonus_awarded: '+20 经验值 光盘奖励已解锁！',
    capture_cancel: '取消扫描',

    // Leaderboard
    lb_title: '校园排行榜',
    lb_tab_bbs: 'BBS PIK',
    lb_tab_goal: '校园目标',
    lb_tab_class: '年级班级',
    lb_top_champion: '当前第一名环保先锋',
    lb_student_rankings: '学生排行榜',
    lb_challenge_title: '校园 1 吨减废挑战',
    lb_challenge_sub: 'BBS PIK 校园可持续行动',
    lb_your_rank: '您的全校排名',
    lb_class_rankings: '各年级粮食减废量',

    // Profile
    profile_title: '学生环保档案',
    profile_edit_picture_hint: '点击更换头像',
    profile_edit_btn: '编辑个人信息',
    profile_summary: '环保成果汇总',
    profile_total_food_saved: '累计节约粮食',
    profile_streak_days: '连续打卡天数',
    profile_badges_unlocked: '已获徽章',
    profile_current_tier: '当前等级',
    profile_badges_heading: '环保荣誉徽章',
    profile_view_all_badges: '查看全部徽章',
    profile_meal_history: '用餐历史记录',

    // Settings
    settings_title: '设置',
    settings_account: '账户',
    settings_edit_profile: '编辑个人信息与头像',
    settings_change_password: '修改密码',
    settings_school_id: '学籍认证',
    settings_preferences: '应用偏好',
    settings_meal_reminders: '用餐打卡提醒',
    settings_challenge_updates: '挑战赛动态通知',
    settings_language: '语言设置',
    settings_greeting_color: '问候昵称与高亮颜色',
    settings_theme: '主题与色彩外观',
    settings_dark_mode: '深色模式',
    settings_dark_desc: '高对比度深色护眼主题',
    settings_light_desc: '清新明亮日间主题',
    settings_sustainability: '可持续发展目标',
    settings_daily_goal: '每日食物拯救目标',
    settings_campus_visibility: '校园公开可见性',
    settings_campus_visibility_desc: '参与 BBS PIK 校园环保挑战',
    settings_support: '帮助与支持',
    settings_faq: '常见问题 (FAQ)',
    settings_contact_us: '联系我们',
    settings_privacy: '隐私政策',
    settings_sign_out: '退出登录',
    settings_sign_out_confirm: '确定要退出 BBS PIK EcoEat 账号吗？',

    // Modals
    modal_edit_profile: '编辑学生个人信息',
    modal_choose_avatar: '选择头像',
    modal_profile_pic: '个人头像',
    modal_custom_photo_active: '已使用自定义照片',
    modal_upload_photo: '上传照片',
    modal_take_photo: '拍照上传',
    modal_link: '图片链接',
    modal_photo_instructions: '从设备上传您的照片 (PNG, JPG, WebP) 或直接拍照。',
    modal_drag_drop: '拖放照片到此处，或点击浏览文件',
    modal_supports_formats: '支持最大 8MB 的各类图片格式',
    modal_apply_url: '应用链接',
    modal_hide_presets: '▼ 隐藏预设头像',
    modal_show_presets: '▶ 或选择示例预设头像',
    modal_full_name: '展示全名',
    modal_greeting_name: '首页问候称呼',
    modal_grade: '年级',
    modal_save_changes: '保存更改',
    modal_pw_title: '修改密码',
    modal_current_pw: '当前密码',
    modal_new_pw: '新密码',
    modal_update_pw: '更新密码',
    modal_pw_updated_title: '密码修改成功！',
    modal_pw_updated_desc: '您的校园学生账号凭据已安全更新。',
    modal_greeting_accent_title: '问候语强调颜色',
    modal_greeting_accent_desc: '自定义 EcoEat 首页标题的称呼字体色彩。',
    modal_theme_title: '外观与色彩主题',
    modal_theme_desc: '个性化定制应用色彩氛围。',
    modal_badge_gallery_title: '校园荣誉徽章图鉴',
    modal_special_title: '校园餐厅今日特色',
    modal_close_special: '关闭特供详情',
    modal_reward_milestone: '奖励里程碑',
    modal_rewards_list: '全校社区奖励：',

    // Toasts
    toast_profile_updated: '个人信息更新成功',
    toast_preferences_saved: '偏好设置已保存',
    toast_language_changed: '语言已切换为',
    toast_greeting_updated: '问候语颜色已更新！',
    toast_signed_out: '已成功退出登录',
    toast_clean_verified: '✨ 光盘验证成功！经验值已计入全校排行榜！',
    toast_level_up: '🎉 升级啦！您已晋升至等级',

    // Authentication & Log-in Page
    auth_header_subtitle: '校园可持续发展与营养中心',
    auth_select_language: '选择语言',
    auth_pitch_badge: '官方校园餐厅与零厨余中心',
    auth_pitch_title_1: '将每一餐转化为',
    auth_pitch_title_2: '校园环保影响力',
    auth_pitch_desc: '扫描您的餐盘，减少食物浪费，为您的年级赚取经验值，助力 BBS PIK 实现本学期 1000 公斤零厨余减废目标。',
    auth_active_students: '名活跃学生',
    auth_food_diverted: '食物已减废',
    auth_feature_sso: '通过 BBS PIK 学生学号与校园邮箱一键登录',
    auth_feature_ai: 'AI 视觉相机自动识别用餐分量与光盘打卡记录',
    auth_feature_rankings: '实时年级竞技排行榜与校园餐厅环保奖励积分',
    auth_tab_signin: '学生登录',
    auth_tab_signup: '创建账号',
    auth_verification_title: '账号验证：',
    auth_verification_desc: '每位 BBS PIK 学生限 1 个官方学籍账号。严禁复制账户或重复注册。',
    auth_label_email_or_id: 'BBS PIK 学生邮箱或学号',
    auth_placeholder_email_or_id: '例如 student.name@bbs-pik.edu',
    auth_label_password: '密码',
    auth_forgot_password: '忘记密码？',
    auth_remember_me: '记住我的学生登录状态',
    auth_btn_signin: '登录校园中心',
    auth_new_to_ecoeat: '初次使用 BBS PIK EcoEat？',
    auth_link_create_account: '立即注册学生账号',
    auth_label_fullname: '学生真实全名',
    auth_placeholder_fullname: '例如 Maya Lin',
    auth_label_grade: '年级',
    auth_label_section: '班级 / 班主任组',
    auth_section_a: 'A 班',
    auth_section_b: 'B 班',
    auth_section_c: 'C 班',
    auth_section_d: 'D 班',
    auth_label_school_email: '学校官方邮箱',
    auth_placeholder_school_email: 'student@bbs-pik.edu',
    auth_label_create_password: '设置密码',
    auth_placeholder_password_len: '至少 6 个字符',
    auth_btn_signup: '加入校园环保计划 (+50 XP)',
    auth_terms_agreement: '注册即表示您同意',
    auth_sustainability_charter: '可持续发展宪章',
    auth_and: '与',
    auth_terms_of_service: '服务条款',
    auth_already_have_account: '已有账号？',
    auth_link_signin: '直接登录',
    auth_reset_pw_title: '重置学生密码',
    auth_reset_pw_desc: '输入您注册的 BBS PIK 学生邮箱。我们将发送一次性重置验证链接到您的学校信箱。',
    auth_btn_send_reset: '发送重置链接',
    auth_reset_sent_title: '密码重置邮件已发送！',
    auth_reset_sent_desc_prefix: '重置指引已发送至',
    auth_reset_sent_desc_suffix: '，请点击邮件中的官方链接设置新密码。',
    auth_btn_return_signin: '返回登录界面',
    auth_hide_password: '隐藏密码',
    auth_show_password: '显示密码',
    auth_footer_bbs: 'Bina Bangsa School',
    auth_footer_pik: 'PIK 校区',
    auth_footer_tagline: 'BBS PIK EcoEat • 2026 校园可持续发展与食物减废示范计划',
    auth_err_email_id_required: '请输入您的 BBS PIK 学生邮箱或学号',
    auth_err_password_required: '请输入您的账号密码',
    auth_err_failed: '身份验证失败，请检查您的凭据。',
    auth_err_name_required: '请输入您的学生完整姓名',
    auth_err_email_required: '请输入有效的 BBS PIK 学生邮箱',
    auth_err_email_invalid: '请输入有效的 BBS PIK 邮箱（例如 name@bbs-pik.edu）',
    auth_err_password_short: '密码长度至少需 6 个字符',
    auth_success_signup: '学生账号创建成功！正在自动登录...',
    auth_err_registration_failed: '账号注册失败。严禁复制已存在的学生学籍账号。',

    // Comprehensive UI Keys
    step: '步骤',
    of: '共',
    clean_plate_bonus_hint: '智能视觉算法自动识别食物种类、营养宏量元素及二氧化碳减排量。',
    finished_fruit_verified: '水果全量食用完成 • 100% 已验证',
    clean_plate_verified: '光盘行动 100% 成功验证',
    finished_fruit_title: '水果完全食用 • 果皮已入堆肥',
    zero_waste_achieved: '零食物浪费目标达成',
    clean_plate_praise: '杰出的校园绿色环保行动！',
    welcome_back: '欢迎回来，',
    tagline: '智慧用餐 • 节约粮食 • 守护绿色',
    current_streak: '连续打卡',
    view_weekly_impact_tooltip: '点击查看本周校园减排影响明细',
    food_saved: '已节约食物',
    eco_diversion_metric: '校园环保分流指标',
    kg: '千克',
    kg_this_week: '千克（本周）',
    view_weekly_impact_action: '周度影响力',
    current_level: '当前等级',
    xp_milestone_rank: '环保经验阶段徽章',
    dashboard_sticker_shop_title: '校园环保专属贴纸商店',
    dashboard_sticker_shop_desc: '用光盘节粮行动赚取的经验值，兑换培民专属环保贴纸与徽章！',
    of_campus_goal: '已达成',
    start_new_meal: '记录新餐食',
    daily_tips: '每日环保贴士',
    recent_meals: '近期用餐记录',
    restart: '重置',
    unlocked: '已解锁',
    profile_stickers_title: '校园环保贴纸',
    profile_stickers_desc: '使用光盘零浪费行动赚取的经验值兑换',
    profile_btn_visit_shop: '贴纸商店',
    profile_no_stickers_title: '你的贴纸图鉴中暂无藏品',
    profile_no_stickers_desc: '前往贴纸商店，使用光盘行动累积的经验值兑换精美的培民校园贴纸！',
    profile_btn_browse_stickers: '探索贴纸商店',
    weekly_impact: '每周环保成果',
    weekly_impact_desc: '按周工作日统计的校园食物减排与光盘数据',
    total_saved: '累计减少浪费',
    settings_language_desc: '选择应用界面显示语言',
    customize: '自定义',
    settings_data_history: '数据与用餐历史',
    restart_recent_meals: '重置近期餐食记录',
    restart_recent_meals_desc: '清空历史用餐记录，重新从0开始记录',
    shop_cat_all: '全部贴纸',
    shop_cat_clean_plate: '🍽️ 光盘行动',
    shop_cat_campus_pride: '🏫 培民校园',
    shop_cat_zero_waste: '♻️ 零废弃物',
    shop_cat_nature_planet: '🌍 地球与海洋',
    shop_cat_culinary: '🥗 绿色美食',
    sticker_rarity_common: '普通',
    sticker_rarity_rare: '稀有',
    sticker_rarity_epic: '史诗',
    sticker_rarity_legendary: '传说',
    shop_badge_tag: '培民学校环保荣誉奖励',
    shop_title: '校园环保贴纸商城',
    shop_subtitle: '通过光盘节粮行动积累经验值，兑换官方定制的校园环保贴纸。探索5大类别，展现你的零浪费环保风采！',
    shop_earn_tip: '每次完成光盘行动，即可为餐食赢取 +25 至 +50 经验值！',
    shop_spendable_balance: '可用经验值余额',
    shop_safe_rank: '历史总等级受保护',
    shop_stickers_owned: '已拥有',
    shop_btn_scan_for_xp: '打卡餐食以获取更多经验值',
    shop_tab_store: '贴纸商城',
    shop_tab_album: '我的贴纸图鉴',
    shop_search_placeholder: '搜索贴纸编号、#ID 或关键词（如 #777777、老虎、青龙）...',
    shop_rarity_filter: '稀有度：',
    shop_showing_count: '显示中',
    shop_collected_label: '张已收藏贴纸',
    shop_stickers_label: '款贴纸',
    shop_album_empty_title: '你的贴纸册目前还是空的！',
    shop_no_stickers_found: '没有找到符合当前筛选条件的贴纸',
    shop_album_empty_desc: '前往贴纸商城，使用光盘积分兑换你的首张校园环保纪念贴纸！',
    shop_try_other_filter: '建议清除搜索词或切换其他贴纸分类查看。',
    shop_btn_browse_store: '前往贴纸商城',
    shop_equipped_badge: '已佩戴',
    shop_click_to_inspect: '查看详情与下载',
    shop_btn_unequip: '卸下',
    shop_btn_equip_showcase: '佩戴至个人资料',
    shop_download_hint: '下载贴纸 PNG 高清图',
    shop_btn_buy: '兑换贴纸',
    shop_need_more_prefix: '还需',
    theme_modal_title: '应用主题与外观',
    theme_modal_subtitle: '个性化定制校园视觉主题与明暗显示模式',
    display_mode_heading: '显示模式',
    dark_mode_title: '深色模式',
    dark_mode_desc: '高对比度，舒适护眼且节省电量',
    light_mode_title: '浅色模式',
    light_mode_desc: '清新明朗的日间布局',
    color_palette_heading: '校园色彩调色板与视觉标识',
    btn_done_apply: '完成并应用外观设置',
    question_food_category_desc: '选择餐食类别以校准 AI 视觉识别准确度与营养宏量指标。',
    question_food_item_desc: '选择热门餐品或在下方搜索',
    search_dish_placeholder: '搜索热门餐食或输入自定义菜品名称...',
    portion_size_heading: '用餐分量',
    btn_proceed_camera: '前往拍摄并扫描餐食',
    btn_verify_clean_plate: '验证光盘并领取环保经验值',
    toast_meals_restarted: '✨ 近期用餐记录已重置为0！',
    toast_signed_out_bbs: '已安全退出培民学校 EcoEat 系统',
    toast_challenge_joined: '🎉 已成功加入校园可持续环保挑战！',
    planned_portion_size: '预计用餐分量',
    selected_dining_profile: '已选餐食档案',
    portion: '分量',
    options_available: '项可选',
    clear: '清除',
    search: '搜索',
    snapshot_captured: '餐食快照拍摄完成',
    starting_camera: '正在启动 AI 视觉取景器...',
    camera_ready: '摄像头已就绪，可随时扫描',
    connecting_camera: '正在连接相机视频流...',
    point_at_food: '对准盘中食物并轻触圆形快门，或直接拍照上传。',
    take_photo_directly: '直接拍照',
    retry_live: '重试实时画面',
    starting_camera_dots: '正在开启相机...',
    active_snapshot: '已截取快照',
    align_clean_plate: '对齐光盘或净餐餐盘',
    center_food_frame: '将餐食或水果对准取景框中央',
  },
};

// Merge extended translations across all supported languages
(Object.keys(translations) as SupportedLanguage[]).forEach((lang) => {
  if (additionalTranslations[lang]) {
    Object.assign(translations[lang], additionalTranslations[lang]);
  }
  if (foodTranslationsByLanguage[lang]) {
    Object.assign(translations[lang], foodTranslationsByLanguage[lang]);
  }
});

interface LanguageContextType {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  t: (key: string, defaultText?: string) => string;
  supportedLanguages: LanguageOption[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{
  children: React.ReactNode;
  initialLanguage?: SupportedLanguage;
  onLanguageChange?: (lang: SupportedLanguage) => void;
}> = ({ children, initialLanguage = 'English', onLanguageChange }) => {
  const [language, setLanguageState] = useState<SupportedLanguage>(() => {
    const saved = localStorage.getItem('ecoeat_language') as SupportedLanguage;
    if (saved && translations[saved]) {
      return saved;
    }
    return initialLanguage;
  });

  useEffect(() => {
    localStorage.setItem('ecoeat_language', language);
    const langObj = SUPPORTED_LANGUAGES.find((l) => l.name === language);
    if (langObj && typeof document !== 'undefined') {
      document.documentElement.lang = langObj.code;
    }
    try {
      const savedSettings = localStorage.getItem('ecoeat_settings');
      if (savedSettings) {
        const parsed = JSON.parse(savedSettings);
        parsed.language = language;
        localStorage.setItem('ecoeat_settings', JSON.stringify(parsed));
      }
    } catch {
      // ignore
    }
    if (onLanguageChange) {
      onLanguageChange(language);
    }
  }, [language, onLanguageChange]);

  const setLanguage = (newLang: SupportedLanguage) => {
    if (translations[newLang]) {
      setLanguageState(newLang);
    }
  };

  const t = (key: string, defaultText?: string): string => {
    const langDict = translations[language] || translations.English;
    if (langDict[key]) {
      return langDict[key];
    }
    if (defaultText && langDict[defaultText]) {
      return langDict[defaultText];
    }
    // Fallback to English
    if (translations.English[key]) {
      return translations.English[key];
    }
    if (defaultText && translations.English[defaultText]) {
      return translations.English[defaultText];
    }
    return defaultText || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
        supportedLanguages: SUPPORTED_LANGUAGES,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
